// T-022 tool-equipment top (scratchpad only): gen_dut_top with the opentitan -pvalue+ values and
// every wrapper port exposed so optimisation cannot sweep the design.
module gen_t022_top import ibex_pkg::*; (
  input  logic                         clk_i,
  input  logic                         rst_ni,
  input  logic [31:0]                  hart_id_i,
  input  logic [31:0]                  boot_addr_i,
  output logic                         instr_req_o,
  input  logic                         instr_gnt_i,
  input  logic                         instr_rvalid_i,
  output logic [31:0]                  instr_addr_o,
  input  logic [38:0]      instr_rdata_i,
  input  logic                         instr_err_i,
  output logic                         data_req_o,
  input  logic                         data_gnt_i,
  input  logic                         data_rvalid_i,
  output logic                         data_we_o,
  output logic [3:0]                   data_be_o,
  output logic [31:0]                  data_addr_o,
  output logic [38:0]      data_wdata_o,
  input  logic [38:0]      data_rdata_i,
  output logic                         data_tag_o,
  input  logic                         data_tag_i,
  input  logic                         data_err_i,
  output logic [1:0]       ic_tag_req_o,
  output logic                         ic_tag_write_o,
  output logic [7:0]        ic_tag_addr_o,
  output logic [27:0]        ic_tag_wdata_o,
  input  logic [27:0]        ic_tag_rdata_i [2],
  output logic [1:0]       ic_data_req_o,
  output logic                         ic_data_write_o,
  output logic [7:0]        ic_data_addr_o,
  output logic [77:0]       ic_data_wdata_o,
  input  logic [77:0]       ic_data_rdata_i [2],
  input  logic                         ic_scr_key_valid_i,
  output logic                         ic_scr_key_req_o,
  input  logic                         irq_software_i,
  input  logic                         irq_timer_i,
  input  logic                         irq_external_i,
  input  logic [14:0]                  irq_fast_i,
  input  logic                         irq_nm_i,
  output logic                         irq_pending_o,
  input  logic                         debug_req_i,
  output crash_dump_t                  crash_dump_o,
  output logic                         double_fault_seen_o,
  input  ibex_mubi_t                   fetch_enable_i,
  input  ibex_mubi_t                   mcounteren_writable_i,
  output logic                         alert_minor_o,
  output logic                         alert_major_internal_o,
  output logic                         alert_major_bus_o,
  output ibex_mubi_t                   core_busy_o
);
  gen_dut_top #(
    .PMPEnable(1'b1), .PMPGranularity(0), .PMPNumRegions(16),
    .MHPMCounterNum(10), .MHPMCounterWidth(32), .RV32E(1'b0),
    .BranchTargetALU(1'b1), .WritebackStage(1'b1), .ICache(1'b1), .ICacheECC(1'b1),
    .ICacheScramble(1'b1), .BranchPredictor(1'b0), .DbgTriggerEn(1'b1), .SecureIbex(1'b1)
  ) u_dut (.*);
endmodule
