"""Rendered by dv/auto_dv/tb/gen_knobs_codegen.py from dv/auto_dv/tb/gen_tb_knobs.yaml; do not edit.
Python mirror of gen_tb_pkg.sv: plusarg names and defaults, regime knob value sets and windows, TB
constants, the memory map and the ISA string (one origin, architecture C11)."""

ISA_STRING = "rv32imc_zicsr_zifencei_zba_zbb_zbc_zbs_zca_zcb_zcmp_zicntr_zihpm_zicclsm_smepmp"

PLUSARGS = {
    "build_config": {"plusarg": "gen_build_config", "kind": "string", "default": 'opentitan', "values": None, "debug_only": False, "desc": 'build configuration name echoed in the banner (must match the compile)'},
    "smoke_cycles": {"plusarg": "gen_smoke_cycles", "kind": "int", "default": 3000, "values": None, "debug_only": False, "desc": 'bounded run length of gen_smoke_tb_top'},
    "smoke_intg_flip": {"plusarg": "gen_smoke_intg_flip", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'smoke red-run knob, bit of the SECDED-encoded NOP word to flip (absent = no corruption)'},
    "dbg_csr_probe": {"plusarg": "gen_dbg_csr_probe", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'probe P6 (docs/gen_probe_register.md), debug only, never in a measured run'},
    "mem_image": {"plusarg": "gen_mem_image", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'program image (.vmem) loaded once at time 0'},
    "mem_image_crc32": {"plusarg": "gen_mem_image_crc32", "kind": "hex", "default": None, "values": None, "debug_only": False, "desc": 'CRC-32 over (index, word) pairs from the .sym.json sidecar, recomputed after load'},
    "mem_image_words": {"plusarg": "gen_mem_image_words", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'word count from the sidecar'},
    "mem_readback_words": {"plusarg": "gen_mem_readback_words", "kind": "int", "default": 64, "values": None, "debug_only": False, "desc": 'words Python reads back through MEM_PEEK and compares with the .vmem'},
    "tohost_addr": {"plusarg": "gen_tohost_addr", "kind": "hex", "default": None, "values": None, "debug_only": False, "desc": 'address of the program tohost word (sidecar symbol); a store there ends the test with the stored code'},
    "mem_unmapped_ok": {"plusarg": "gen_mem_unmapped_ok", "kind": "bool", "default": 0, "values": None, "debug_only": False, "desc": 'unmapped bus access returns an error response instead of a TB error'},
    "boot_addr": {"plusarg": "gen_boot_addr", "kind": "hex", "default": 2147483648, "values": None, "debug_only": False, "desc": 'boot_addr_i (must match the image entry page)'},
    "hart_id": {"plusarg": "gen_hart_id", "kind": "hex", "default": 0, "values": None, "debug_only": False, "desc": 'hart_id_i (architecture C1)'},
    "alive_timeout": {"plusarg": "gen_alive_timeout", "kind": "int", "default": 100000, "values": None, "debug_only": False, "desc": 'cycles before the SV alive watchdog fatals (TB_CONTRACT Section 2)'},
    "finish_timeout": {"plusarg": "gen_finish_timeout", "kind": "int", "default": 20000, "values": None, "debug_only": False, "desc": 'finish-handshake budget in cycles used by GenBridge.finish() when the test passes none'},
    "regime_sched": {"plusarg": "gen_regime_sched", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'layer-3 schedule knob:value@r<N>|c<N>,... (consumed when supplied, else derived from RANDOM_SEED and echoed)'},
    "rvfi_trace": {"plusarg": "gen_rvfi_trace", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'print every RVFI record (debug only)'},
    "fcov_en": {"plusarg": "gen_fcov_en", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'instantiate covergroups'},
    "icram_init": {"plusarg": "gen_icram_init", "kind": "enum", "default": 'random', "values": ['zero', 'random'], "debug_only": False, "desc": 'initial contents of the icache tag/data RAM models'},
    "fetch_en_at_reset": {"plusarg": "gen_fetch_en_at_reset", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'fetch_enable_i On out of reset; 0 holds the core until a bridge FETCH_EN command (image read-back happens first)'},
    "key_reset_valid": {"plusarg": "gen_key_reset_valid", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ic_scr_key_valid_i high out of reset (ibex_top behaviour)'},
    "sb_trace": {"plusarg": "gen_sb_trace", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'scoreboard per-record trace (debug only)'},
    "isa_string": {"plusarg": "gen_isa_string", "kind": "string", "default": None, "values": None, "debug_only": True, "desc": 'model ISA string override (debug only; the default is GEN_ISA_STRING)'},
    "isa_log": {"plusarg": "gen_isa_log", "kind": "string", "default": None, "values": None, "debug_only": True, "desc": 'model commit log path (debug only)'},
    "export_file": {"plusarg": "gen_export_file", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'record/event export file (relative to the run directory); absent = no export'},
    "export_counters": {"plusarg": "gen_export_counters", "kind": "bool", "default": 0, "values": None, "debug_only": False, "desc": 'append the hpm counter words to every R line of the export'},
    "export_sources": {"plusarg": "gen_export_sources", "kind": "string", "default": 'all', "values": None, "debug_only": False, "desc": 'comma-separated event sources written to the export (all = every source with a registered writer)'},
    "export_flush_every": {"plusarg": "gen_export_flush_every", "kind": "int", "default": 0, "values": None, "debug_only": True, "desc": 'flush the export file every n records for triage of abnormal ends (0 = only on EXPORT_FLUSH)'},
    "ut_boot_retire": {"plusarg": "gen_ut_boot_retire", "kind": "int", "default": 200, "values": None, "debug_only": False, "desc": 'retirements the boots-and-retires test waits for'},
    "ibus_gnt_min": {"plusarg": "gen_ibus_gnt_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus grant latency low bound (cycles)'},
    "ibus_gnt_max": {"plusarg": "gen_ibus_gnt_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus grant latency high bound'},
    "ibus_rvalid_min": {"plusarg": "gen_ibus_rvalid_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus response latency low bound (hard floor 1)'},
    "ibus_rvalid_max": {"plusarg": "gen_ibus_rvalid_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus response latency high bound'},
    "ibus_max_outstanding": {"plusarg": "gen_ibus_max_outstanding", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'grants in flight before gnt is withheld (cap GEN_IBUS_MAX_OUTSTANDING)'},
    "ibus_err_rate": {"plusarg": "gen_ibus_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of instr_err_i per response'},
    "ibus_intg_err_rate": {"plusarg": "gen_ibus_intg_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of corrupting instr_rdata_i integrity'},
    "ibus_intg_bits": {"plusarg": "gen_ibus_intg_bits", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'bits flipped per corrupted instruction response (1 or 2)'},
    "ibus_err_window": {"plusarg": "gen_ibus_err_window", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'lo:hi address window where injected instruction errors apply'},
    "dbus_gnt_min": {"plusarg": "gen_dbus_gnt_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus grant latency low bound'},
    "dbus_gnt_max": {"plusarg": "gen_dbus_gnt_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus grant latency high bound'},
    "dbus_rvalid_min": {"plusarg": "gen_dbus_rvalid_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus response latency low bound (hard floor 1)'},
    "dbus_rvalid_max": {"plusarg": "gen_dbus_rvalid_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus response latency high bound'},
    "dbus_max_outstanding": {"plusarg": "gen_dbus_max_outstanding", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data grants in flight (cap GEN_DBUS_MAX_OUTSTANDING)'},
    "dbus_err_rate": {"plusarg": "gen_dbus_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of data_err_i per response'},
    "dbus_intg_err_rate": {"plusarg": "gen_dbus_intg_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of corrupting data_rdata_i integrity'},
    "dbus_intg_bits": {"plusarg": "gen_dbus_intg_bits", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'bits flipped per corrupted data response'},
    "dbus_err_window": {"plusarg": "gen_dbus_err_window", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'lo:hi address window where injected data errors apply'},
    "dbus_err_half": {"plusarg": "gen_dbus_err_half", "kind": "enum", "default": 'any', "values": ['first', 'second', 'both', 'any'], "debug_only": False, "desc": 'which half of a split access an injected error hits'},
    "dbus_err_store_perform": {"plusarg": "gen_dbus_err_store_perform", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'an errored store still updates the memory model'},
    "key_delay_min": {"plusarg": "gen_key_delay_min", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'scramble-key response delay low bound'},
    "key_delay_max": {"plusarg": "gen_key_delay_max", "kind": "int", "default": 20, "values": None, "debug_only": False, "desc": 'scramble-key response delay high bound'},
    "key_never_cycles": {"plusarg": "gen_key_never_cycles", "kind": "int", "default": 0, "values": None, "debug_only": False, "desc": 'cycles the key stays withheld in the withheld_then_valid regime'},
    "irq_min_gap": {"plusarg": "gen_irq_min_gap", "kind": "int", "default": 0, "values": None, "debug_only": False, "desc": 'minimum cycles between interrupt events'},
    "irq_hold_min": {"plusarg": "gen_irq_hold_min", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'interrupt line hold low bound (CYCLES policy)'},
    "irq_hold_max": {"plusarg": "gen_irq_hold_max", "kind": "int", "default": 50, "values": None, "debug_only": False, "desc": 'interrupt line hold high bound'},
    "dbg_hold_min": {"plusarg": "gen_dbg_hold_min", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'debug_req_i hold low bound'},
    "dbg_hold_max": {"plusarg": "gen_dbg_hold_max", "kind": "int", "default": 50, "values": None, "debug_only": False, "desc": 'debug_req_i hold high bound'},
    "knob_imem_gnt_delay": {"plusarg": "gen_knob_imem_gnt_delay", "kind": "enum", "default": 'short', "values": ['same_cycle', 'short', 'long', 'random'], "debug_only": False, "desc": 'instruction grant latency regime (windows: regime_windows.gnt_delay)'},
    "knob_imem_rvalid_delay": {"plusarg": "gen_knob_imem_rvalid_delay", "kind": "enum", "default": 'short', "values": ['min1', 'short', 'long', 'random'], "debug_only": False, "desc": 'instruction response latency regime (windows: regime_windows.rvalid_delay)'},
    "knob_imem_err_rate": {"plusarg": "gen_knob_imem_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'instr_err_i injection regime (rates: regime_windows.rate_per_mille)'},
    "knob_imem_intg_err_rate": {"plusarg": "gen_knob_imem_intg_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'instruction integrity corruption regime (rates: regime_windows.rate_per_mille)'},
    "knob_imem_outstanding_cap": {"plusarg": "gen_knob_imem_outstanding_cap", "kind": "enum", "default": 'cap8', "values": ['cap1', 'cap2', 'cap4', 'cap8'], "debug_only": False, "desc": 'instruction grants in flight cap (regime_windows.outstanding_cap)'},
    "knob_dmem_gnt_delay": {"plusarg": "gen_knob_dmem_gnt_delay", "kind": "enum", "default": 'short', "values": ['same_cycle', 'short', 'long', 'random'], "debug_only": False, "desc": 'data grant latency regime (windows: regime_windows.gnt_delay)'},
    "knob_dmem_rvalid_delay": {"plusarg": "gen_knob_dmem_rvalid_delay", "kind": "enum", "default": 'short', "values": ['min1', 'short', 'long', 'random'], "debug_only": False, "desc": 'data response latency regime (windows: regime_windows.rvalid_delay)'},
    "knob_dmem_err_rate": {"plusarg": "gen_knob_dmem_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'data_err_i injection regime (rates: regime_windows.rate_per_mille)'},
    "knob_dmem_intg_err_rate": {"plusarg": "gen_knob_dmem_intg_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'data integrity corruption regime (rates: regime_windows.rate_per_mille)'},
    "knob_irq_regime": {"plusarg": "gen_knob_irq_regime", "kind": "enum", "default": 'quiet', "values": ['quiet', 'sparse', 'storm'], "debug_only": False, "desc": 'interrupt event rate'},
    "knob_irq_line_mix": {"plusarg": "gen_knob_irq_line_mix", "kind": "enum", "default": 'single', "values": ['single', 'multi', 'fast_only', 'with_nmi'], "debug_only": False, "desc": 'lines per interrupt event'},
    "knob_irq_hold": {"plusarg": "gen_knob_irq_hold", "kind": "enum", "default": 'until_taken', "values": ['until_taken', 'through_handler', 'pulse'], "debug_only": False, "desc": 'interrupt line release policy'},
    "knob_debug_req_regime": {"plusarg": "gen_knob_debug_req_regime", "kind": "enum", "default": 'none', "values": ['none', 'sparse', 'storm'], "debug_only": False, "desc": 'debug_req_i event rate'},
    "knob_scr_key_delay": {"plusarg": "gen_knob_scr_key_delay", "kind": "enum", "default": 'immediate', "values": ['immediate', 'delayed', 'withheld_then_valid'], "debug_only": False, "desc": 'scramble-key response regime'},
    "knob_icache_ecc_err_rate": {"plusarg": "gen_knob_icache_ecc_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'icache RAM ECC injection regime'},
    "knob_fetch_enable_regime": {"plusarg": "gen_knob_fetch_enable_regime", "kind": "enum", "default": 'always_on', "values": ['always_on', 'toggling'], "debug_only": False, "desc": 'fetch_enable_i regime'},
    "knob_mcounteren_writable": {"plusarg": "gen_knob_mcounteren_writable", "kind": "enum", "default": 'on', "values": ['on', 'off', 'invalid'], "debug_only": False, "desc": 'mcounteren_writable_i encoding'},
    "knob_instr_mix": {"plusarg": "gen_knob_instr_mix", "kind": "enum", "default": 'mixed', "values": ['isa_only', 'm_heavy', 'compressed_heavy', 'bitmanip_heavy', 'csr_heavy', 'ls_heavy', 'branch_heavy', 'mixed'], "debug_only": False, "desc": 'program-side instruction mix (region marker)'},
    "knob_priv_regime": {"plusarg": "gen_knob_priv_regime", "kind": "enum", "default": 'm_only', "values": ['m_only', 'u_heavy', 'alternating'], "debug_only": False, "desc": 'program-side privilege regime (region marker)'},
    "knob_pmp_regime": {"plusarg": "gen_knob_pmp_regime", "kind": "enum", "default": 'off', "values": ['off', 'sparse', 'dense', 'mml_on'], "debug_only": False, "desc": 'program-side PMP regime (region marker)'},
    "chk_all": {"plusarg": "gen_chk_all", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'master checker enable (isolation mode +gen_chk_all=0 +gen_chk_<id>=1)'},
    "chk_ibus_proto": {"plusarg": "gen_chk_ibus_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ibus_outstanding": {"plusarg": "gen_chk_ibus_outstanding", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_sva_rvalid_legal": {"plusarg": "gen_chk_sva_rvalid_legal", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'TB self-check enable (stimulus legality)'},
    "chk_dbus_proto": {"plusarg": "gen_chk_dbus_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbus_outstanding": {"plusarg": "gen_chk_dbus_outstanding", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbus_split": {"plusarg": "gen_chk_dbus_split", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbus_store_intg": {"plusarg": "gen_chk_dbus_store_intg", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_icram_write_ecc": {"plusarg": "gen_chk_icram_write_ecc", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_icram_inval_sweep": {"plusarg": "gen_chk_icram_inval_sweep", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_icram_ecc_response": {"plusarg": "gen_chk_icram_ecc_response", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_scrkey_proto": {"plusarg": "gen_chk_scrkey_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_alert_minor": {"plusarg": "gen_chk_alert_minor", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_alert_bus": {"plusarg": "gen_chk_alert_bus", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_alert_internal": {"plusarg": "gen_chk_alert_internal", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_crash_dump": {"plusarg": "gen_chk_crash_dump", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_double_fault": {"plusarg": "gen_chk_double_fault", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_core_busy": {"plusarg": "gen_chk_core_busy", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_data_tag_quiet": {"plusarg": "gen_chk_data_tag_quiet", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_fetch_en": {"plusarg": "gen_chk_fetch_en", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_irq_pending": {"plusarg": "gen_chk_irq_pending", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_irq_entry": {"plusarg": "gen_chk_irq_entry", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_irq_masked": {"plusarg": "gen_chk_irq_masked", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_nmi_entry": {"plusarg": "gen_chk_nmi_entry", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_nmi_internal": {"plusarg": "gen_chk_nmi_internal", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_entry": {"plusarg": "gen_chk_dbg_entry", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_exc": {"plusarg": "gen_chk_dbg_exc", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_masked": {"plusarg": "gen_chk_dbg_masked", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_dret": {"plusarg": "gen_chk_dbg_dret", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_trigger": {"plusarg": "gen_chk_dbg_trigger", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_mcycle": {"plusarg": "gen_chk_ctr_mcycle", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_minstret": {"plusarg": "gen_chk_ctr_minstret", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_hpm_exact": {"plusarg": "gen_chk_ctr_hpm_exact", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_hpm_bound": {"plusarg": "gen_chk_ctr_hpm_bound", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_pmp_data": {"plusarg": "gen_chk_pmp_data", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_pmp_fetch": {"plusarg": "gen_chk_pmp_fetch", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_isa": {"plusarg": "gen_chk_isa", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA comparator master enable'},
    "chk_isa_pc": {"plusarg": "gen_chk_isa_pc", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_insn": {"plusarg": "gen_chk_isa_insn", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_trap": {"plusarg": "gen_chk_isa_trap", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_rd": {"plusarg": "gen_chk_isa_rd", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_mem": {"plusarg": "gen_chk_isa_mem", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_prv": {"plusarg": "gen_chk_isa_prv", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_pc_next": {"plusarg": "gen_chk_isa_pc_next", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_csr": {"plusarg": "gen_chk_isa_csr", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_rvfi_proto": {"plusarg": "gen_chk_rvfi_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'RVFI stream sanity assertions (monitor)'},
    "chk_t022_never": {"plusarg": "gen_chk_t022_never", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'rtl-arch T-022 never-arc asserts in the binds home'},
    "chk_bridge_accounting": {"plusarg": "gen_chk_bridge_accounting", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'TB self-check enable'},
}

CONSTANTS = {
    "GEN_ICACHE_NUM_FB": 4,
    "GEN_IBUS_MAX_OUTSTANDING": 8,
    "GEN_DBUS_MAX_OUTSTANDING": 2,
    "GEN_CSR_WRITE_TO_RVFI_OFFSET": 2,
    "GEN_TRAP_TO_RVFI_OFFSET": 1,
    "GEN_IRQ_MARKER_TO_RVFI_OFFSET": 2,
    "GEN_RVFI_ID_EXIT_OFFSET": 2,
    "GEN_ICACHE_ECC_WINDOW": 1,
    "GEN_IRQ_ENTRY_BOUND_RECORDS": 17,
    "GEN_DBG_ENTRY_BOUND_RECORDS": 17,
    "GEN_CLK_PERIOD_NS": 10,
    "GEN_MEM_READBACK_WORDS_DEFAULT": 64,
    "GEN_ALIVE_TIMEOUT_CYCLES_DEFAULT": 100000,
    "GEN_FINISH_TIMEOUT_CYCLES_DEFAULT": 20000,
    "GEN_IRQ_FAST_W": 15,
    "GEN_IRQ_FAST_MASK": 2147418112,
}

REGIME_WINDOWS = {  # group -> value -> [lo, hi] (latencies) or scalar (rates per mille, caps)
    "gnt_delay": {"same_cycle": [0, 0], "short": [1, 3], "long": [4, 32], "random": [0, 32]},
    "outstanding_cap": {"cap1": 1, "cap2": 2, "cap4": 4, "cap8": 8},
    "rate_per_mille": {"none": 0, "rare": 2, "frequent": 50},
    "rvalid_delay": {"min1": [1, 1], "short": [2, 4], "long": [5, 32], "random": [1, 32]},
}

KNOB_IDS = {  # regime knob -> REGIME_SET arg0; value index = position in PLUSARGS[name]['values']
    "knob_imem_gnt_delay": 0,
    "knob_imem_rvalid_delay": 1,
    "knob_imem_err_rate": 2,
    "knob_imem_intg_err_rate": 3,
    "knob_imem_outstanding_cap": 4,
    "knob_dmem_gnt_delay": 5,
    "knob_dmem_rvalid_delay": 6,
    "knob_dmem_err_rate": 7,
    "knob_dmem_intg_err_rate": 8,
    "knob_irq_regime": 9,
    "knob_irq_line_mix": 10,
    "knob_irq_hold": 11,
    "knob_debug_req_regime": 12,
    "knob_scr_key_delay": 13,
    "knob_icache_ecc_err_rate": 14,
    "knob_fetch_enable_regime": 15,
    "knob_mcounteren_writable": 16,
    "knob_instr_mix": 17,
    "knob_priv_regime": 18,
    "knob_pmp_regime": 19,
}

CMD = {  # bridge command kinds (cmd_kind codes)
    "IRQ_SET": 1,
    "IRQ_CLR": 2,
    "NMI_PULSE": 3,
    "DBG_REQ": 4,
    "REGIME_SET": 5,
    "KEY_MODE": 6,
    "MEM_ERR_ARM": 7,
    "ICACHE_ECC_ARM": 8,
    "FETCH_EN": 9,
    "MEM_PEEK": 10,
    "MISC": 11,
    "EXPORT_FLUSH": 12,
}

EXPORT_RECORD_FIELDS = ('order', 'pc_rdata', 'pc_wdata', 'insn', 'trap', 'halt', 'intr', 'mode', 'ixl', 'rs1_addr', 'rs1_rdata', 'rs2_addr', 'rs2_rdata', 'rs3_addr', 'rs3_rdata', 'rd_addr', 'rd_wdata', 'mem_addr', 'mem_rmask', 'mem_wmask', 'mem_rdata', 'mem_wdata', 'ext_pre_mip', 'ext_post_mip', 'ext_nmi', 'ext_nmi_int', 'ext_debug_req', 'ext_debug_mode', 'ext_rf_wr_suppress', 'ext_ic_scr_key_valid', 'ext_irq_valid', 'ext_exp_valid', 'ext_exp_insn', 'ext_exp_last', 'ext_mcycle', 'cycle')
EXPORT_COUNTER_FIELDS = ('mhpmcounter3', 'mhpmcounter4', 'mhpmcounter5', 'mhpmcounter6', 'mhpmcounter7', 'mhpmcounter8', 'mhpmcounter9', 'mhpmcounter10', 'mhpmcounter11', 'mhpmcounter12', 'mhpmcounter3h', 'mhpmcounter4h', 'mhpmcounter5h', 'mhpmcounter6h', 'mhpmcounter7h', 'mhpmcounter8h', 'mhpmcounter9h', 'mhpmcounter10h', 'mhpmcounter11h', 'mhpmcounter12h')
EXPORT_SOURCES = ('ibus', 'dbus', 'pin', 'alert', 'misc', 'icram', 'scrkey', 'regime')
EXPORT_EVENTS = (  # (source, event or '<name>', fields)
    ('ibus', 'req', ('addr', 'we', 'be')),
    ('ibus', 'gnt', ('addr', 'we', 'be', 'req_cycle', 'outstanding_after')),
    ('ibus', 'rvalid', ('addr', 'we', 'err', 'intg_injected', 'outstanding_after')),
    ('dbus', 'req', ('addr', 'we', 'be')),
    ('dbus', 'gnt', ('addr', 'we', 'be', 'req_cycle', 'outstanding_after')),
    ('dbus', 'rvalid', ('addr', 'we', 'err', 'intg_injected', 'outstanding_after')),
    ('pin', '<name>', ('value',)),
    ('alert', '<name>', ('value',)),
    ('misc', '<name>', ('value',)),
    ('icram', 'inject', ('way', 'index')),
    ('scrkey', '<name>', ('value',)),
    ('regime', 'phase', ('knob_id', 'value_idx', 'phase_idx')),
)

MEMORY_MAP = {
    "boot_addr_default": 0x80000000,
    "boot_page_mask": 0xffffff00,
    "boot_page": 0x80000000,
    "prog_size": 0x00100000,
    "dm_base": 0x1a110000,
    "dm_size": 0x00001000,
    "dm_halt": 0x1a110800,
    "dm_exception": 0x1a110808,
    "dm_budget": 0x00000800,
    "mmio_base": 0x8ffff000,
    "mmio_size": 0x00001000,
    "sig_addr": 0x8ffff000,
    "sig_size": 0x00000100,
    "irq_ack_addr": 0x8ffff100,
    "irq_ack_size": 0x00000004,
    "eot_addr": 0x8ffff104,
    "eot_size": 0x00000004,
    "phase_mark_addr": 0x8ffff108,
    "phase_mark_size": 0x00000004,
}

DEBUG_ONLY = [p["plusarg"] for p in PLUSARGS.values() if p["debug_only"]]
CHECKERS = [n[4:] for n in PLUSARGS if n.startswith("chk_") and n != "chk_all"]

def plusarg(name, value=None):
    """+gen_<name>[=value] as passed on the simv command line."""
    p = PLUSARGS[name]
    return f"+{p['plusarg']}" if value is None else f"+{p['plusarg']}={value}"
