"""Rendered by dv/auto_dv/tb/gen_knobs_codegen.py from dv/auto_dv/tb/gen_tb_knobs.yaml; do not edit.
Python mirror of gen_tb_pkg.sv: plusarg names and defaults, regime knob value sets and windows, TB
constants, the memory map and the ISA string (one origin, architecture C11)."""

ISA_STRING = "rv32imc_zicsr_zifencei_zba_zbb_zbc_zbs_zca_zcb_zcmp_zicntr_zihpm_zicclsm_smepmp"

PLUSARGS = {
    "build_config": {"plusarg": "gen_build_config", "kind": "string", "default": 'opentitan', "values": None, "debug_only": False, "desc": 'build configuration name echoed in the banner (must match the compile)'},
    "smoke_cycles": {"plusarg": "gen_smoke_cycles", "kind": "int", "default": 3000, "values": None, "debug_only": False, "desc": 'bounded run length of gen_smoke_tb_top'},
    "smoke_intg_flip": {"plusarg": "gen_smoke_intg_flip", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'smoke red-run knob, bit of the SECDED-encoded NOP word to flip (absent = no corruption)'},
    "dbg_csr_probe": {"plusarg": "gen_dbg_csr_probe", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'probe P6 (docs/gen_probe_register.md), debug only, never in a measured run'},
    "mem_image": {"plusarg": "gen_mem_image", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'program image (.vmem) loaded once at time 0'},
    "mem_image_crc32": {"plusarg": "gen_mem_image_crc32", "kind": "hex", "default": None, "values": None, "debug_only": False, "desc": 'CRC-32 over (index, word) pairs from the .sym.json sidecar, recomputed after load'},
    "mem_image_words": {"plusarg": "gen_mem_image_words", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'word count from the sidecar'},
    "mem_readback_words": {"plusarg": "gen_mem_readback_words", "kind": "int", "default": 64, "values": None, "debug_only": False, "desc": 'words Python reads back through MEM_PEEK and compares with the .vmem'},
    "tohost_addr": {"plusarg": "gen_tohost_addr", "kind": "hex", "default": None, "values": None, "debug_only": False, "desc": 'address of the program tohost word (sidecar symbol); a store there ends the test with the stored code'},
    "mem_unmapped_ok": {"plusarg": "gen_mem_unmapped_ok", "kind": "bool", "default": 0, "values": None, "debug_only": False, "desc": 'unmapped bus access returns an error response instead of a TB error'},
    "boot_addr": {"plusarg": "gen_boot_addr", "kind": "hex", "default": 2147483648, "values": None, "debug_only": False, "desc": 'boot_addr_i (must match the image entry page)'},
    "hart_id": {"plusarg": "gen_hart_id", "kind": "hex", "default": 0, "values": None, "debug_only": False, "desc": 'hart_id_i (architecture C1)'},
    "alive_timeout": {"plusarg": "gen_alive_timeout", "kind": "int", "default": 100000, "values": None, "debug_only": False, "desc": 'cycles before the SV alive watchdog fatals (TB_CONTRACT Section 2)'},
    "finish_timeout": {"plusarg": "gen_finish_timeout", "kind": "int", "default": 20000, "values": None, "debug_only": False, "desc": 'finish-handshake budget in cycles used by GenBridge.finish() when the test passes none'},
    "regime_sched": {"plusarg": "gen_regime_sched", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'layer-3 schedule knob:value@r<N>|c<N>,... (consumed when supplied, else derived from RANDOM_SEED and echoed)'},
    "rvfi_trace": {"plusarg": "gen_rvfi_trace", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'print every RVFI record (debug only)'},
    "fcov_en": {"plusarg": "gen_fcov_en", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'instantiate covergroups'},
    "icram_init": {"plusarg": "gen_icram_init", "kind": "enum", "default": 'random', "values": ['zero', 'random'], "debug_only": False, "desc": 'initial contents of the icache tag/data RAM models'},
    "fetch_en_at_reset": {"plusarg": "gen_fetch_en_at_reset", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'fetch_enable_i On out of reset; 0 holds the core until a bridge FETCH_EN command (image read-back happens first)'},
    "key_reset_valid": {"plusarg": "gen_key_reset_valid", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ic_scr_key_valid_i high out of reset (ibex_top behaviour)'},
    "sb_trace": {"plusarg": "gen_sb_trace", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'scoreboard per-record trace (debug only)'},
    "isa_pc_next_mask_b13": {"plusarg": "gen_isa_pc_next_mask_b13", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'isa_pc_next masks bit 0 of rvfi_pc_wdata on jalr records (bug candidate B13, rtl-arch R11); 0 = the raw rule, for the expected-fail test of the odd-target report'},
    "isa_string": {"plusarg": "gen_isa_string", "kind": "string", "default": None, "values": None, "debug_only": True, "desc": 'model ISA string override (debug only; the default is GEN_ISA_STRING)'},
    "isa_log": {"plusarg": "gen_isa_log", "kind": "string", "default": None, "values": None, "debug_only": True, "desc": 'model commit log path (debug only)'},
    "export_file": {"plusarg": "gen_export_file", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'record/event export file (relative to the run directory); absent = no export'},
    "export_counters": {"plusarg": "gen_export_counters", "kind": "bool", "default": 0, "values": None, "debug_only": False, "desc": 'append the hpm counter words to every R line of the export'},
    "export_sources": {"plusarg": "gen_export_sources", "kind": "string", "default": 'all', "values": None, "debug_only": False, "desc": 'comma-separated event sources written to the export (all = every source with a registered writer)'},
    "export_flush_every": {"plusarg": "gen_export_flush_every", "kind": "int", "default": 0, "values": None, "debug_only": True, "desc": 'flush the export file every n records for triage of abnormal ends (0 = only on EXPORT_FLUSH)'},
    "ut_boot_retire": {"plusarg": "gen_ut_boot_retire", "kind": "int", "default": 200, "values": None, "debug_only": False, "desc": 'retirements the boots-and-retires test waits for'},
    "ut_fcov_query": {"plusarg": "gen_ut_fcov_query", "kind": "int", "default": -1, "values": None, "debug_only": False, "desc": 'gen_ut_isa_cov: the sampler counter index to compare (FCOV_QUERY), -1 for none'},
    "ut_fcov_expect": {"plusarg": "gen_ut_fcov_expect", "kind": "int", "default": 0, "values": None, "debug_only": False, "desc": 'gen_ut_isa_cov: the value the program is known to produce for that counter'},
    "ut_rows_set": {"plusarg": "gen_ut_rows_set", "kind": "enum", "default": 'regime_nmi', "values": ['regime_nmi', 'regime_dbg'], "debug_only": False, "desc": 'gen_ut_export_rows: the pin row exercised beside regime phase (irq_nm through NMI_PULSE, or debug_req through DBG_REQ)'},
    "ibus_gnt_min": {"plusarg": "gen_ibus_gnt_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus grant latency low bound (cycles)'},
    "ibus_gnt_max": {"plusarg": "gen_ibus_gnt_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus grant latency high bound'},
    "ibus_rvalid_min": {"plusarg": "gen_ibus_rvalid_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus response latency low bound (hard floor 1)'},
    "ibus_rvalid_max": {"plusarg": "gen_ibus_rvalid_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'instruction bus response latency high bound'},
    "ibus_max_outstanding": {"plusarg": "gen_ibus_max_outstanding", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'grants in flight before gnt is withheld (cap GEN_IBUS_MAX_OUTSTANDING)'},
    "ibus_err_rate": {"plusarg": "gen_ibus_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of instr_err_i per response'},
    "ibus_intg_err_rate": {"plusarg": "gen_ibus_intg_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of corrupting instr_rdata_i integrity'},
    "ibus_intg_bits": {"plusarg": "gen_ibus_intg_bits", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'bits flipped per corrupted instruction response (1 or 2)'},
    "ibus_err_window": {"plusarg": "gen_ibus_err_window", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'lo:hi address window where injected instruction errors apply'},
    "dbus_gnt_min": {"plusarg": "gen_dbus_gnt_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus grant latency low bound'},
    "dbus_gnt_max": {"plusarg": "gen_dbus_gnt_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus grant latency high bound'},
    "dbus_rvalid_min": {"plusarg": "gen_dbus_rvalid_min", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus response latency low bound (hard floor 1)'},
    "dbus_rvalid_max": {"plusarg": "gen_dbus_rvalid_max", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data bus response latency high bound'},
    "dbus_max_outstanding": {"plusarg": "gen_dbus_max_outstanding", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'data grants in flight (cap GEN_DBUS_MAX_OUTSTANDING)'},
    "dbus_err_rate": {"plusarg": "gen_dbus_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of data_err_i per response'},
    "dbus_intg_err_rate": {"plusarg": "gen_dbus_intg_err_rate", "kind": "int", "default": None, "values": None, "debug_only": False, "desc": 'per-mille probability of corrupting data_rdata_i integrity'},
    "dbus_intg_bits": {"plusarg": "gen_dbus_intg_bits", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'bits flipped per corrupted data response'},
    "dbus_err_window": {"plusarg": "gen_dbus_err_window", "kind": "string", "default": None, "values": None, "debug_only": False, "desc": 'lo:hi address window where injected data errors apply'},
    "dbus_err_half": {"plusarg": "gen_dbus_err_half", "kind": "enum", "default": 'any', "values": ['first', 'second', 'both', 'any'], "debug_only": False, "desc": 'which half of a split access an injected error hits'},
    "dbus_err_store_perform": {"plusarg": "gen_dbus_err_store_perform", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'an errored store still updates the memory model'},
    "key_delay_min": {"plusarg": "gen_key_delay_min", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'scramble-key response delay low bound'},
    "key_delay_max": {"plusarg": "gen_key_delay_max", "kind": "int", "default": 20, "values": None, "debug_only": False, "desc": 'scramble-key response delay high bound'},
    "key_never_cycles": {"plusarg": "gen_key_never_cycles", "kind": "int", "default": 0, "values": None, "debug_only": False, "desc": 'cycles the key stays withheld in the withheld_then_valid regime'},
    "irq_min_gap": {"plusarg": "gen_irq_min_gap", "kind": "int", "default": 0, "values": None, "debug_only": False, "desc": 'minimum cycles between interrupt events'},
    "irq_hold_min": {"plusarg": "gen_irq_hold_min", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'interrupt line hold low bound (CYCLES policy)'},
    "irq_hold_max": {"plusarg": "gen_irq_hold_max", "kind": "int", "default": 50, "values": None, "debug_only": False, "desc": 'interrupt line hold high bound'},
    "dbg_hold_min": {"plusarg": "gen_dbg_hold_min", "kind": "int", "default": 1, "values": None, "debug_only": False, "desc": 'debug_req_i hold low bound'},
    "dbg_hold_max": {"plusarg": "gen_dbg_hold_max", "kind": "int", "default": 50, "values": None, "debug_only": False, "desc": 'debug_req_i hold high bound'},
    "knob_imem_gnt_delay": {"plusarg": "gen_knob_imem_gnt_delay", "kind": "enum", "default": 'short', "values": ['same_cycle', 'short', 'long', 'random'], "debug_only": False, "desc": 'instruction grant latency regime (windows: regime_windows.gnt_delay)'},
    "knob_imem_rvalid_delay": {"plusarg": "gen_knob_imem_rvalid_delay", "kind": "enum", "default": 'short', "values": ['min1', 'short', 'long', 'random'], "debug_only": False, "desc": 'instruction response latency regime (windows: regime_windows.rvalid_delay)'},
    "knob_imem_err_rate": {"plusarg": "gen_knob_imem_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'instr_err_i injection regime (rates: regime_windows.rate_per_mille)'},
    "knob_imem_intg_err_rate": {"plusarg": "gen_knob_imem_intg_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'instruction integrity corruption regime (rates: regime_windows.rate_per_mille)'},
    "knob_imem_outstanding_cap": {"plusarg": "gen_knob_imem_outstanding_cap", "kind": "enum", "default": 'cap8', "values": ['cap1', 'cap2', 'cap4', 'cap8'], "debug_only": False, "desc": 'instruction grants in flight cap (regime_windows.outstanding_cap)'},
    "knob_dmem_gnt_delay": {"plusarg": "gen_knob_dmem_gnt_delay", "kind": "enum", "default": 'short', "values": ['same_cycle', 'short', 'long', 'random'], "debug_only": False, "desc": 'data grant latency regime (windows: regime_windows.gnt_delay)'},
    "knob_dmem_rvalid_delay": {"plusarg": "gen_knob_dmem_rvalid_delay", "kind": "enum", "default": 'short', "values": ['min1', 'short', 'long', 'random'], "debug_only": False, "desc": 'data response latency regime (windows: regime_windows.rvalid_delay)'},
    "knob_dmem_err_rate": {"plusarg": "gen_knob_dmem_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'data_err_i injection regime (rates: regime_windows.rate_per_mille)'},
    "knob_dmem_intg_err_rate": {"plusarg": "gen_knob_dmem_intg_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'data integrity corruption regime (rates: regime_windows.rate_per_mille)'},
    "knob_irq_regime": {"plusarg": "gen_knob_irq_regime", "kind": "enum", "default": 'quiet', "values": ['quiet', 'sparse', 'storm'], "debug_only": False, "desc": 'interrupt event rate'},
    "knob_irq_line_mix": {"plusarg": "gen_knob_irq_line_mix", "kind": "enum", "default": 'single', "values": ['single', 'multi', 'fast_only', 'with_nmi'], "debug_only": False, "desc": 'lines per interrupt event'},
    "knob_irq_hold": {"plusarg": "gen_knob_irq_hold", "kind": "enum", "default": 'until_taken', "values": ['until_taken', 'through_handler', 'pulse'], "debug_only": False, "desc": 'interrupt line release policy'},
    "knob_debug_req_regime": {"plusarg": "gen_knob_debug_req_regime", "kind": "enum", "default": 'none', "values": ['none', 'sparse', 'storm'], "debug_only": False, "desc": 'debug_req_i event rate'},
    "knob_scr_key_delay": {"plusarg": "gen_knob_scr_key_delay", "kind": "enum", "default": 'immediate', "values": ['immediate', 'delayed', 'withheld_then_valid'], "debug_only": False, "desc": 'scramble-key response regime'},
    "knob_icache_ecc_err_rate": {"plusarg": "gen_knob_icache_ecc_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": 'icache tag-RAM ECC injection regime (rates: regime_windows.rate_per_mille): the tag RAM models flip one bit of a lookup read at the rate and announce it through gen_icram_events; the misc monitor expects alert_minor_o within GEN_ICACHE_ECC_WINDOW of every qualified injection'},
    "knob_icache_data_ecc_err_rate": {"plusarg": "gen_knob_icache_data_ecc_err_rate", "kind": "enum", "default": 'none', "values": ['none', 'rare', 'frequent'], "debug_only": False, "desc": "icache data-RAM ECC injection regime (rates: regime_windows.rate_per_mille): the data RAM models flip bits of a lookup read at the rate and announce it through gen_icram_events with the injected way's stored tag state; the misc monitor owes a pulse only when the way was valid and was the way the lookup hit; the lookup tag comes from the P9 probe in evidence runs and from the retirement stream in measured runs"},
    "knob_icache_ecc_bits": {"plusarg": "gen_knob_icache_ecc_bits", "kind": "enum", "default": 'one', "values": ['one', 'two'], "debug_only": False, "desc": 'bits flipped per icache ECC injection on both RAM kinds: one, or two distinct positions (a detected two-bit error alerts and invalidates as a one-bit error does)'},
    "knob_fetch_enable_regime": {"plusarg": "gen_knob_fetch_enable_regime", "kind": "enum", "default": 'always_on', "values": ['always_on', 'toggling'], "debug_only": False, "desc": 'fetch_enable_i regime'},
    "knob_mcounteren_writable": {"plusarg": "gen_knob_mcounteren_writable", "kind": "enum", "default": 'on', "values": ['on', 'off', 'invalid'], "debug_only": False, "desc": 'mcounteren_writable_i encoding'},
    "knob_instr_mix": {"plusarg": "gen_knob_instr_mix", "kind": "enum", "default": 'mixed', "values": ['isa_only', 'm_heavy', 'compressed_heavy', 'bitmanip_heavy', 'csr_heavy', 'ls_heavy', 'branch_heavy', 'mixed'], "debug_only": False, "desc": 'program-side instruction mix (region marker)'},
    "knob_priv_regime": {"plusarg": "gen_knob_priv_regime", "kind": "enum", "default": 'm_only', "values": ['m_only', 'u_heavy', 'alternating'], "debug_only": False, "desc": 'program-side privilege regime (region marker)'},
    "knob_pmp_regime": {"plusarg": "gen_knob_pmp_regime", "kind": "enum", "default": 'off', "values": ['off', 'sparse', 'dense', 'mml_on'], "debug_only": False, "desc": 'program-side PMP regime (region marker)'},
    "chk_all": {"plusarg": "gen_chk_all", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'master checker enable (isolation mode +gen_chk_all=0 +gen_chk_<id>=1)'},
    "chk_ibus_proto": {"plusarg": "gen_chk_ibus_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ibus_outstanding": {"plusarg": "gen_chk_ibus_outstanding", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_sva_st": {"plusarg": "gen_chk_sva_st", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_st_*)'},
    "chk_sva_ibus": {"plusarg": "gen_chk_sva_ibus", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_ibus_*)'},
    "chk_sva_dbus": {"plusarg": "gen_chk_sva_dbus", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_dbus_*)'},
    "chk_sva_icram": {"plusarg": "gen_chk_sva_icram", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_icram_*)'},
    "chk_sva_scrkey": {"plusarg": "gen_chk_sva_scrkey", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_scrkey_*)'},
    "chk_sva_irq": {"plusarg": "gen_chk_sva_irq", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_irq_*)'},
    "chk_sva_dbg": {"plusarg": "gen_chk_sva_dbg", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_dbg_*)'},
    "chk_sva_alert": {"plusarg": "gen_chk_sva_alert", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_alert_*)'},
    "chk_sva_rvfi": {"plusarg": "gen_chk_sva_rvfi", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'protocol SVA group enable, gen_binds.sv (gen_protocol_props ids sva_rvfi_*)'},
    "chk_sva_b8": {"plusarg": "gen_chk_sva_b8", "kind": "bool", "default": 0, "values": None, "debug_only": False, "desc": 'the B8 probe assertion sva_b8_dummy_in_expansion (gen_b8_probe.sv bound into ibex_if_stage, LOG-067): off by default because the DUT fails it on every dummy insertion inside a Zcmp expansion; the reproducer runs enable it'},
    "probe_ic_lookup": {"plusarg": "gen_probe_ic_lookup", "kind": "bool", "default": 0, "values": None, "debug_only": True, "desc": 'the P9 probe (docs/gen_probe_register.md, LOG-079): gen_ic_lookup_probe.sv bound into ibex_icache publishes the lookup tag the DUT compares, so the misc monitor derives the hit way for data-RAM ECC injections; read-only, off by default, debug only (never in a measured run)'},
    "chk_sva_rvalid_legal": {"plusarg": "gen_chk_sva_rvalid_legal", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'TB self-check enable (stimulus legality)'},
    "chk_dbus_proto": {"plusarg": "gen_chk_dbus_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbus_outstanding": {"plusarg": "gen_chk_dbus_outstanding", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbus_split": {"plusarg": "gen_chk_dbus_split", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbus_store_intg": {"plusarg": "gen_chk_dbus_store_intg", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_icram_write_ecc": {"plusarg": "gen_chk_icram_write_ecc", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_icram_inval_sweep": {"plusarg": "gen_chk_icram_inval_sweep", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_icram_ecc_response": {"plusarg": "gen_chk_icram_ecc_response", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_scrkey_proto": {"plusarg": "gen_chk_scrkey_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_alert_minor": {"plusarg": "gen_chk_alert_minor", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_alert_bus": {"plusarg": "gen_chk_alert_bus", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_alert_internal": {"plusarg": "gen_chk_alert_internal", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_crash_dump": {"plusarg": "gen_chk_crash_dump", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_double_fault": {"plusarg": "gen_chk_double_fault", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_core_busy": {"plusarg": "gen_chk_core_busy", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_data_tag_quiet": {"plusarg": "gen_chk_data_tag_quiet", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_fetch_en": {"plusarg": "gen_chk_fetch_en", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_irq_pending": {"plusarg": "gen_chk_irq_pending", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_irq_entry": {"plusarg": "gen_chk_irq_entry", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_irq_masked": {"plusarg": "gen_chk_irq_masked", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_nmi_entry": {"plusarg": "gen_chk_nmi_entry", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_nmi_internal": {"plusarg": "gen_chk_nmi_internal", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_entry": {"plusarg": "gen_chk_dbg_entry", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_exc": {"plusarg": "gen_chk_dbg_exc", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_masked": {"plusarg": "gen_chk_dbg_masked", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_dret": {"plusarg": "gen_chk_dbg_dret", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_dbg_trigger": {"plusarg": "gen_chk_dbg_trigger", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_mcycle": {"plusarg": "gen_chk_ctr_mcycle", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_minstret": {"plusarg": "gen_chk_ctr_minstret", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_hpm_exact": {"plusarg": "gen_chk_ctr_hpm_exact", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_ctr_hpm_bound": {"plusarg": "gen_chk_ctr_hpm_bound", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_pmp_data": {"plusarg": "gen_chk_pmp_data", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_pmp_fetch": {"plusarg": "gen_chk_pmp_fetch", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'checker enable'},
    "chk_isa": {"plusarg": "gen_chk_isa", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA comparator master enable'},
    "chk_isa_pc": {"plusarg": "gen_chk_isa_pc", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_insn": {"plusarg": "gen_chk_isa_insn", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_trap": {"plusarg": "gen_chk_isa_trap", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_rd": {"plusarg": "gen_chk_isa_rd", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_mem": {"plusarg": "gen_chk_isa_mem", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_prv": {"plusarg": "gen_chk_isa_prv", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_pc_next": {"plusarg": "gen_chk_isa_pc_next", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_isa_csr": {"plusarg": "gen_chk_isa_csr", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'ISA compare field enable'},
    "chk_rvfi_proto": {"plusarg": "gen_chk_rvfi_proto", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'RVFI stream sanity assertions (monitor)'},
    "chk_t022_never": {"plusarg": "gen_chk_t022_never", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'rtl-arch T-022 never-arc asserts in the binds home'},
    "chk_bridge_accounting": {"plusarg": "gen_chk_bridge_accounting", "kind": "bool", "default": 1, "values": None, "debug_only": False, "desc": 'TB self-check enable'},
}

CONSTANTS = {
    "GEN_ICACHE_NUM_FB": 4,
    "GEN_IBUS_MAX_OUTSTANDING": 8,
    "GEN_DBUS_MAX_OUTSTANDING": 2,
    "GEN_CSR_WRITE_TO_RVFI_OFFSET": 2,
    "GEN_TRAP_TO_RVFI_OFFSET": 1,
    "GEN_FETCH_EN_DRAIN_CYCLES": 64,
    "GEN_LSU_TRAP_TO_RVFI_OFFSET": 0,
    "GEN_IRQ_MARKER_TO_RVFI_OFFSET": 2,
    "GEN_RVFI_ID_EXIT_OFFSET": 2,
    "GEN_ICACHE_ECC_WINDOW": 2,
    "GEN_ICACHE_ECC_GRACE_CYCLES": 16,
    "GEN_ICRAM_UNINIT_Q_DEPTH": 512,
    "GEN_ICACHE_RETIRE_WINDOW": 64,
    "GEN_IRQ_ENTRY_BOUND_RECORDS": 17,
    "GEN_DBG_ENTRY_BOUND_RECORDS": 17,
    "GEN_CLK_PERIOD_NS": 10,
    "GEN_MEM_READBACK_WORDS_DEFAULT": 64,
    "GEN_ALIVE_TIMEOUT_CYCLES_DEFAULT": 100000,
    "GEN_FINISH_TIMEOUT_CYCLES_DEFAULT": 20000,
    "GEN_IRQ_FAST_W": 15,
    "GEN_IRQ_FAST_MASK": 2147418112,
    "GEN_CSR_MARCHID_VALUE": 22,
    "GEN_CSR_CPUCTRLSTS": 1984,
    "GEN_CSR_SECURESEED": 1985,
    "GEN_MHPM_COUNTER_NUM": 10,
    "GEN_INSN_MRET": 807403635,
    "GEN_INSN_DRET": 2065694835,
    "GEN_TDATA1_IBEX_RDATA": 671092808,
    "GEN_CPUCTRLSTS_SYNC_EXC_SEEN_BIT": 6,
    "GEN_CPUCTRLSTS_DOUBLE_FAULT_SEEN_BIT": 7,
    "GEN_CPUCTRLSTS_ICACHE_ENABLE_BIT": 0,
    "GEN_CPUCTRLSTS_DATA_IND_TIMING_BIT": 1,
    "GEN_CPUCTRLSTS_DUMMY_INSTR_EN_BIT": 2,
    "GEN_DCSR_PRV_BIT_LOW": 0,
    "GEN_DCSR_PRV_BIT_HIGH": 1,
    "GEN_CAUSE_NMI_EXTERNAL": 2147483679,
    "GEN_CAUSE_NMI_INTERNAL": 4294967264,
    "GEN_MEM_ERR_ARM_KIND_ERR": 1,
    "GEN_BUS_ERR_LOG_DEPTH": 256,
    "GEN_BUS_ERR_DRAIN_CYCLES": 96,
    "GEN_NMI_INT_ENTRY_BOUND_RECORDS": 4,
    "GEN_MEM_ERR_ARM_KIND_INTG": 2,
    "GEN_ISA_FAULT_KIND_FETCH": 0,
    "GEN_ISA_FAULT_KIND_LOAD": 1,
    "GEN_ISA_FAULT_KIND_STORE": 2,
}

REGIME_WINDOWS = {  # group -> value -> [lo, hi] (latencies) or scalar (rates per mille, caps)
    "dbg_event_mean": {"none": 0, "sparse": 5000, "storm": 200},
    "gnt_delay": {"same_cycle": [0, 0], "short": [1, 3], "long": [4, 32], "random": [0, 32]},
    "irq_event_mean": {"quiet": 0, "sparse": 2000, "storm": 100},
    "outstanding_cap": {"cap1": 1, "cap2": 2, "cap4": 4, "cap8": 8},
    "rate_per_mille": {"none": 0, "rare": 2, "frequent": 50},
    "rvalid_delay": {"min1": [1, 1], "short": [2, 4], "long": [5, 32], "random": [1, 32]},
}

KNOB_IDS = {  # regime knob -> REGIME_SET arg0; value index = position in PLUSARGS[name]['values']
    "knob_imem_gnt_delay": 0,
    "knob_imem_rvalid_delay": 1,
    "knob_imem_err_rate": 2,
    "knob_imem_intg_err_rate": 3,
    "knob_imem_outstanding_cap": 4,
    "knob_dmem_gnt_delay": 5,
    "knob_dmem_rvalid_delay": 6,
    "knob_dmem_err_rate": 7,
    "knob_dmem_intg_err_rate": 8,
    "knob_irq_regime": 9,
    "knob_irq_line_mix": 10,
    "knob_irq_hold": 11,
    "knob_debug_req_regime": 12,
    "knob_scr_key_delay": 13,
    "knob_icache_ecc_err_rate": 14,
    "knob_icache_data_ecc_err_rate": 15,
    "knob_icache_ecc_bits": 16,
    "knob_fetch_enable_regime": 17,
    "knob_mcounteren_writable": 18,
    "knob_instr_mix": 19,
    "knob_priv_regime": 20,
    "knob_pmp_regime": 21,
}

KNOB_CONSUMER = {  # regime knob -> yaml regime_set_consumer (bus, irq, dbg, scrkey, none, program)
    "knob_imem_gnt_delay": "bus",
    "knob_imem_rvalid_delay": "bus",
    "knob_imem_err_rate": "bus",
    "knob_imem_intg_err_rate": "bus",
    "knob_imem_outstanding_cap": "bus",
    "knob_dmem_gnt_delay": "bus",
    "knob_dmem_rvalid_delay": "bus",
    "knob_dmem_err_rate": "bus",
    "knob_dmem_intg_err_rate": "bus",
    "knob_irq_regime": "irq",
    "knob_irq_line_mix": "irq",
    "knob_irq_hold": "irq",
    "knob_debug_req_regime": "dbg",
    "knob_scr_key_delay": "scrkey",
    "knob_icache_ecc_err_rate": "none",
    "knob_icache_data_ecc_err_rate": "none",
    "knob_icache_ecc_bits": "none",
    "knob_fetch_enable_regime": "none",
    "knob_mcounteren_writable": "none",
    "knob_instr_mix": "program",
    "knob_priv_regime": "program",
    "knob_pmp_regime": "program",
}

# knobs the SV dispatcher consumes at run time (REGIME_SET); the test library's CONSUMED_KNOBS reads this
REGIME_SET_CONSUMED = ("knob_imem_gnt_delay", "knob_imem_rvalid_delay", "knob_imem_err_rate", "knob_imem_intg_err_rate", "knob_imem_outstanding_cap", "knob_dmem_gnt_delay", "knob_dmem_rvalid_delay", "knob_dmem_err_rate", "knob_dmem_intg_err_rate", "knob_irq_regime", "knob_irq_line_mix", "knob_irq_hold", "knob_debug_req_regime", "knob_scr_key_delay",)

CMD = {  # bridge command kinds (cmd_kind codes)
    "IRQ_SET": 1,
    "IRQ_CLR": 2,
    "NMI_PULSE": 3,
    "DBG_REQ": 4,
    "REGIME_SET": 5,
    "KEY_MODE": 6,
    "MEM_ERR_ARM": 7,
    "ICACHE_ECC_ARM": 8,
    "FETCH_EN": 9,
    "MEM_PEEK": 10,
    "MISC": 11,
    "EXPORT_FLUSH": 12,
    "COV_WITNESS": 13,
    "FCOV_SELFTEST": 14,
    "FCOV_QUERY": 15,
}

EXPORT_RECORD_FIELDS = ('order', 'pc_rdata', 'pc_wdata', 'insn', 'trap', 'halt', 'intr', 'mode', 'ixl', 'rs1_addr', 'rs1_rdata', 'rs2_addr', 'rs2_rdata', 'rs3_addr', 'rs3_rdata', 'rd_addr', 'rd_wdata', 'mem_addr', 'mem_rmask', 'mem_wmask', 'mem_rdata', 'mem_wdata', 'ext_pre_mip', 'ext_post_mip', 'ext_nmi', 'ext_nmi_int', 'ext_debug_req', 'ext_debug_mode', 'ext_rf_wr_suppress', 'ext_ic_scr_key_valid', 'ext_irq_valid', 'ext_exp_valid', 'ext_exp_insn', 'ext_exp_last', 'ext_mcycle', 'cycle')
EXPORT_COUNTER_FIELDS = ('mhpmcounter3', 'mhpmcounter4', 'mhpmcounter5', 'mhpmcounter6', 'mhpmcounter7', 'mhpmcounter8', 'mhpmcounter9', 'mhpmcounter10', 'mhpmcounter11', 'mhpmcounter12', 'mhpmcounter3h', 'mhpmcounter4h', 'mhpmcounter5h', 'mhpmcounter6h', 'mhpmcounter7h', 'mhpmcounter8h', 'mhpmcounter9h', 'mhpmcounter10h', 'mhpmcounter11h', 'mhpmcounter12h')
EXPORT_SOURCES = ('ibus', 'dbus', 'pin', 'alert', 'misc', 'icram', 'scrkey', 'regime')
EXPORT_ACTIVE_SOURCES = ('ibus', 'dbus', 'pin', 'alert', 'misc', 'scrkey', 'regime')  # sources whose writers are instanced in this build (yaml export_active_sources)
EXPORT_EVENTS = (  # (source, event, fields); one exact event per row
    ('ibus', 'req', ('addr', 'we', 'be')),
    ('ibus', 'gnt', ('addr', 'we', 'be', 'req_cycle', 'outstanding_after')),
    ('ibus', 'rvalid', ('addr', 'we', 'err', 'intg_injected', 'outstanding_after')),
    ('dbus', 'req', ('addr', 'we', 'be')),
    ('dbus', 'gnt', ('addr', 'we', 'be', 'req_cycle', 'outstanding_after')),
    ('dbus', 'rvalid', ('addr', 'we', 'err', 'intg_injected', 'outstanding_after')),
    ('pin', 'irq_software', ('value',)),
    ('pin', 'irq_timer', ('value',)),
    ('pin', 'irq_external', ('value',)),
    ('pin', 'irq_fast', ('idx', 'value')),
    ('pin', 'irq_nm', ('value',)),
    ('pin', 'debug_req', ('value',)),
    ('pin', 'fetch_enable', ('value',)),
    ('pin', 'mcounteren_writable', ('value',)),
    ('alert', 'alert_minor', ('value',)),
    ('alert', 'alert_major_bus', ('value',)),
    ('alert', 'alert_major_internal', ('value',)),
    ('alert', 'double_fault_seen', ('value',)),
    ('misc', 'irq_pending', ('value',)),
    ('misc', 'irq_entry', ('order', 'cause', 'decidable')),
    ('misc', 'core_busy', ('value',)),
    ('misc', 'crash_dump_current_pc', ('value',)),
    ('misc', 'crash_dump_next_pc', ('value',)),
    ('misc', 'crash_dump_last_data_addr', ('value',)),
    ('misc', 'crash_dump_exception_pc', ('value',)),
    ('misc', 'crash_dump_exception_addr', ('value',)),
    ('icram', 'inject', ('way', 'index')),
    ('icram', 'lookup', ('index',)),
    ('icram', 'tag_write', ('way', 'index', 'valid')),
    ('icram', 'fill_write', ('way', 'index')),
    ('scrkey', 'req', ('value',)),
    ('scrkey', 'valid', ('value',)),
    ('regime', 'phase', ('knob_id', 'value_idx', 'phase_idx')),
)

# CG-WIT-001 witness protocol (COV_WITNESS arg0 = WITNESS_IDS[tp], arg1 = WITNESS_GROUPS[the issuing test's group])
WITNESS_IDS = {'TP-BIT-036': 0, 'TP-BIT-042': 1, 'TP-BIT-043': 2, 'TP-BTALU-001': 3, 'TP-BTALU-012': 4, 'TP-BTALU-018': 5, 'TP-CMP-057': 6, 'TP-CMP-058': 7, 'TP-CSR-029': 8, 'TP-CSR-031': 9, 'TP-CSR-034': 10, 'TP-CSR-085': 11, 'TP-CSR-090': 12, 'TP-CSR-100': 13, 'TP-DBG-003': 14, 'TP-DBG-004': 15, 'TP-DBG-005': 16, 'TP-DBG-006': 17, 'TP-DBG-007': 18, 'TP-DBG-008': 19, 'TP-DBG-009': 20, 'TP-DBG-011': 21, 'TP-DBG-014': 22, 'TP-DBG-021': 23, 'TP-DBG-030': 24, 'TP-DBG-046': 25, 'TP-DBG-049': 26, 'TP-DBG-051': 27, 'TP-DBG-054': 28, 'TP-DBG-061': 29, 'TP-DBG-063': 30, 'TP-DBG-071': 31, 'TP-DMEM-002': 32, 'TP-DMEM-004': 33, 'TP-DMEM-005': 34, 'TP-DMEM-006': 35, 'TP-DMEM-007': 36, 'TP-DMEM-008': 37, 'TP-DMEM-019': 38, 'TP-DMEM-020': 39, 'TP-DMEM-021': 40, 'TP-DMEM-022': 41, 'TP-DMEM-027': 42, 'TP-DMEM-034': 43, 'TP-DMEM-037': 44, 'TP-DMEM-039': 45, 'TP-DMEM-044': 46, 'TP-DMEM-046': 47, 'TP-DMEM-047': 48, 'TP-DMEM-049': 49, 'TP-DMEM-051': 50, 'TP-DMEM-056': 51, 'TP-DMEM-057': 52, 'TP-DMEM-058': 53, 'TP-DMEM-059': 54, 'TP-DMEM-061': 55, 'TP-DMEM-062': 56, 'TP-DMEM-063': 57, 'TP-DMEM-064': 58, 'TP-EXC-015': 59, 'TP-EXC-034': 60, 'TP-EXC-035': 61, 'TP-EXC-036': 62, 'TP-EXC-037': 63, 'TP-EXC-038': 64, 'TP-EXC-040': 65, 'TP-EXC-050': 66, 'TP-EXC-054': 67, 'TP-EXC-055': 68, 'TP-EXC-057': 69, 'TP-EXC-062': 70, 'TP-EXC-065': 71, 'TP-EXC-070': 72, 'TP-EXC-072': 73, 'TP-FE-008': 74, 'TP-FE-012': 75, 'TP-FE-013': 76, 'TP-FE-014': 77, 'TP-FE-016': 78, 'TP-FE-017': 79, 'TP-FE-022': 80, 'TP-FE-026': 81, 'TP-IC-002': 82, 'TP-IC-003': 83, 'TP-IC-004': 84, 'TP-IC-005': 85, 'TP-IC-007': 86, 'TP-IC-008': 87, 'TP-IC-011': 88, 'TP-IC-015': 89, 'TP-IC-019': 90, 'TP-IC-020': 91, 'TP-IC-023': 92, 'TP-IC-024': 93, 'TP-IC-030': 94, 'TP-IC-031': 95, 'TP-IC-035': 96, 'TP-IC-036': 97, 'TP-IC-037': 98, 'TP-IC-045': 99, 'TP-IC-046': 100, 'TP-IC-051': 101, 'TP-IC-052': 102, 'TP-IC-053': 103, 'TP-IC-057': 104, 'TP-IMEM-001': 105, 'TP-IMEM-003': 106, 'TP-IMEM-004': 107, 'TP-IMEM-005': 108, 'TP-IMEM-006': 109, 'TP-IMEM-007': 110, 'TP-IMEM-008': 111, 'TP-IMEM-010': 112, 'TP-IMEM-014': 113, 'TP-IMEM-016': 114, 'TP-IMEM-017': 115, 'TP-IMEM-018': 116, 'TP-IMEM-022': 117, 'TP-IMEM-023': 118, 'TP-IMEM-025': 119, 'TP-IMEM-027': 120, 'TP-IMEM-033': 121, 'TP-IMEM-036': 122, 'TP-IMEM-037': 123, 'TP-IMEM-039': 124, 'TP-IMEM-040': 125, 'TP-IRQ-009': 126, 'TP-IRQ-011': 127, 'TP-IRQ-015': 128, 'TP-IRQ-021': 129, 'TP-IRQ-022': 130, 'TP-IRQ-023': 131, 'TP-IRQ-024': 132, 'TP-IRQ-025': 133, 'TP-IRQ-026': 134, 'TP-IRQ-027': 135, 'TP-IRQ-030': 136, 'TP-IRQ-031': 137, 'TP-IRQ-038': 138, 'TP-IRQ-039': 139, 'TP-IRQ-041': 140, 'TP-IRQ-044': 141, 'TP-IRQ-045': 142, 'TP-IRQ-049': 143, 'TP-IRQ-050': 144, 'TP-IRQ-051': 145, 'TP-IRQ-052': 146, 'TP-IRQ-053': 147, 'TP-IRQ-054': 148, 'TP-IRQ-055': 149, 'TP-IRQ-057': 150, 'TP-IRQ-059': 151, 'TP-IRQ-061': 152, 'TP-IRQ-064': 153, 'TP-IRQ-066': 154, 'TP-IRQ-068': 155, 'TP-IRQ-070': 156, 'TP-IRQ-072': 157, 'TP-IRQ-073': 158, 'TP-IRQ-077': 159, 'TP-IRQ-078': 160, 'TP-IRQ-079': 161, 'TP-IRQ-080': 162, 'TP-ISA-024': 163, 'TP-ISA-040': 164, 'TP-ISA-051': 165, 'TP-MUL-011': 166, 'TP-MUL-023': 167, 'TP-MUL-024': 168, 'TP-PMC-001': 169, 'TP-PMC-002': 170, 'TP-PMC-011': 171, 'TP-PMC-013': 172, 'TP-PMC-016': 173, 'TP-PMC-024': 174, 'TP-PMC-028': 175, 'TP-PMC-034': 176, 'TP-PMC-047': 177, 'TP-PMC-058': 178, 'TP-PMC-059': 179, 'TP-PMC-060': 180, 'TP-PMP-053': 181, 'TP-PMP-077': 182, 'TP-PMP-082': 183, 'TP-PMP-091': 184, 'TP-PMP-105': 185, 'TP-PRV-018': 186, 'TP-PRV-019': 187, 'TP-REG-001': 188, 'TP-REG-002': 189, 'TP-REG-005': 190, 'TP-REG-006': 191, 'TP-REG-008': 192, 'TP-REG-010': 193, 'TP-REG-011': 194, 'TP-REG-012': 195, 'TP-REG-018': 196, 'TP-REG-020': 197, 'TP-REG-021': 198, 'TP-REG-023': 199, 'TP-REG-026': 200, 'TP-REG-027': 201, 'TP-TRG-019': 202, 'TP-TRG-023': 203, 'TP-TRG-025': 204, 'TP-TRG-026': 205, 'TP-TRG-027': 206, 'TP-XIF-001': 207, 'TP-XIF-002': 208, 'TP-XIF-003': 209, 'TP-XIF-004': 210, 'TP-XIF-008': 211, 'TP-XIF-009': 212, 'TP-XIF-010': 213, 'TP-XIF-011': 214, 'TP-XIF-012': 215, 'TP-XIF-014': 216, 'TP-XIF-015': 217, 'TP-XIF-016': 218, 'TP-XIF-017': 219}
WITNESS_BINS = {'TP-BIT-036': 'w_tp_bit_036', 'TP-BIT-042': 'w_tp_bit_042', 'TP-BIT-043': 'w_tp_bit_043', 'TP-BTALU-001': 'w_tp_btalu_001', 'TP-BTALU-012': 'w_tp_btalu_012', 'TP-BTALU-018': 'w_tp_btalu_018', 'TP-CMP-057': 'w_tp_cmp_057', 'TP-CMP-058': 'w_tp_cmp_058', 'TP-CSR-029': 'w_tp_csr_029', 'TP-CSR-031': 'w_tp_csr_031', 'TP-CSR-034': 'w_tp_csr_034', 'TP-CSR-085': 'w_tp_csr_085', 'TP-CSR-090': 'w_tp_csr_090', 'TP-CSR-100': 'w_tp_csr_100', 'TP-DBG-003': 'w_tp_dbg_003', 'TP-DBG-004': 'w_tp_dbg_004', 'TP-DBG-005': 'w_tp_dbg_005', 'TP-DBG-006': 'w_tp_dbg_006', 'TP-DBG-007': 'w_tp_dbg_007', 'TP-DBG-008': 'w_tp_dbg_008', 'TP-DBG-009': 'w_tp_dbg_009', 'TP-DBG-011': 'w_tp_dbg_011', 'TP-DBG-014': 'w_tp_dbg_014', 'TP-DBG-021': 'w_tp_dbg_021', 'TP-DBG-030': 'w_tp_dbg_030', 'TP-DBG-046': 'w_tp_dbg_046', 'TP-DBG-049': 'w_tp_dbg_049', 'TP-DBG-051': 'w_tp_dbg_051', 'TP-DBG-054': 'w_tp_dbg_054', 'TP-DBG-061': 'w_tp_dbg_061', 'TP-DBG-063': 'w_tp_dbg_063', 'TP-DBG-071': 'w_tp_dbg_071', 'TP-DMEM-002': 'w_tp_dmem_002', 'TP-DMEM-004': 'w_tp_dmem_004', 'TP-DMEM-005': 'w_tp_dmem_005', 'TP-DMEM-006': 'w_tp_dmem_006', 'TP-DMEM-007': 'w_tp_dmem_007', 'TP-DMEM-008': 'w_tp_dmem_008', 'TP-DMEM-019': 'w_tp_dmem_019', 'TP-DMEM-020': 'w_tp_dmem_020', 'TP-DMEM-021': 'w_tp_dmem_021', 'TP-DMEM-022': 'w_tp_dmem_022', 'TP-DMEM-027': 'w_tp_dmem_027', 'TP-DMEM-034': 'w_tp_dmem_034', 'TP-DMEM-037': 'w_tp_dmem_037', 'TP-DMEM-039': 'w_tp_dmem_039', 'TP-DMEM-044': 'w_tp_dmem_044', 'TP-DMEM-046': 'w_tp_dmem_046', 'TP-DMEM-047': 'w_tp_dmem_047', 'TP-DMEM-049': 'w_tp_dmem_049', 'TP-DMEM-051': 'w_tp_dmem_051', 'TP-DMEM-056': 'w_tp_dmem_056', 'TP-DMEM-057': 'w_tp_dmem_057', 'TP-DMEM-058': 'w_tp_dmem_058', 'TP-DMEM-059': 'w_tp_dmem_059', 'TP-DMEM-061': 'w_tp_dmem_061', 'TP-DMEM-062': 'w_tp_dmem_062', 'TP-DMEM-063': 'w_tp_dmem_063', 'TP-DMEM-064': 'w_tp_dmem_064', 'TP-EXC-015': 'w_tp_exc_015', 'TP-EXC-034': 'w_tp_exc_034', 'TP-EXC-035': 'w_tp_exc_035', 'TP-EXC-036': 'w_tp_exc_036', 'TP-EXC-037': 'w_tp_exc_037', 'TP-EXC-038': 'w_tp_exc_038', 'TP-EXC-040': 'w_tp_exc_040', 'TP-EXC-050': 'w_tp_exc_050', 'TP-EXC-054': 'w_tp_exc_054', 'TP-EXC-055': 'w_tp_exc_055', 'TP-EXC-057': 'w_tp_exc_057', 'TP-EXC-062': 'w_tp_exc_062', 'TP-EXC-065': 'w_tp_exc_065', 'TP-EXC-070': 'w_tp_exc_070', 'TP-EXC-072': 'w_tp_exc_072', 'TP-FE-008': 'w_tp_fe_008', 'TP-FE-012': 'w_tp_fe_012', 'TP-FE-013': 'w_tp_fe_013', 'TP-FE-014': 'w_tp_fe_014', 'TP-FE-016': 'w_tp_fe_016', 'TP-FE-017': 'w_tp_fe_017', 'TP-FE-022': 'w_tp_fe_022', 'TP-FE-026': 'w_tp_fe_026', 'TP-IC-002': 'w_tp_ic_002', 'TP-IC-003': 'w_tp_ic_003', 'TP-IC-004': 'w_tp_ic_004', 'TP-IC-005': 'w_tp_ic_005', 'TP-IC-007': 'w_tp_ic_007', 'TP-IC-008': 'w_tp_ic_008', 'TP-IC-011': 'w_tp_ic_011', 'TP-IC-015': 'w_tp_ic_015', 'TP-IC-019': 'w_tp_ic_019', 'TP-IC-020': 'w_tp_ic_020', 'TP-IC-023': 'w_tp_ic_023', 'TP-IC-024': 'w_tp_ic_024', 'TP-IC-030': 'w_tp_ic_030', 'TP-IC-031': 'w_tp_ic_031', 'TP-IC-035': 'w_tp_ic_035', 'TP-IC-036': 'w_tp_ic_036', 'TP-IC-037': 'w_tp_ic_037', 'TP-IC-045': 'w_tp_ic_045', 'TP-IC-046': 'w_tp_ic_046', 'TP-IC-051': 'w_tp_ic_051', 'TP-IC-052': 'w_tp_ic_052', 'TP-IC-053': 'w_tp_ic_053', 'TP-IC-057': 'w_tp_ic_057', 'TP-IMEM-001': 'w_tp_imem_001', 'TP-IMEM-003': 'w_tp_imem_003', 'TP-IMEM-004': 'w_tp_imem_004', 'TP-IMEM-005': 'w_tp_imem_005', 'TP-IMEM-006': 'w_tp_imem_006', 'TP-IMEM-007': 'w_tp_imem_007', 'TP-IMEM-008': 'w_tp_imem_008', 'TP-IMEM-010': 'w_tp_imem_010', 'TP-IMEM-014': 'w_tp_imem_014', 'TP-IMEM-016': 'w_tp_imem_016', 'TP-IMEM-017': 'w_tp_imem_017', 'TP-IMEM-018': 'w_tp_imem_018', 'TP-IMEM-022': 'w_tp_imem_022', 'TP-IMEM-023': 'w_tp_imem_023', 'TP-IMEM-025': 'w_tp_imem_025', 'TP-IMEM-027': 'w_tp_imem_027', 'TP-IMEM-033': 'w_tp_imem_033', 'TP-IMEM-036': 'w_tp_imem_036', 'TP-IMEM-037': 'w_tp_imem_037', 'TP-IMEM-039': 'w_tp_imem_039', 'TP-IMEM-040': 'w_tp_imem_040', 'TP-IRQ-009': 'w_tp_irq_009', 'TP-IRQ-011': 'w_tp_irq_011', 'TP-IRQ-015': 'w_tp_irq_015', 'TP-IRQ-021': 'w_tp_irq_021', 'TP-IRQ-022': 'w_tp_irq_022', 'TP-IRQ-023': 'w_tp_irq_023', 'TP-IRQ-024': 'w_tp_irq_024', 'TP-IRQ-025': 'w_tp_irq_025', 'TP-IRQ-026': 'w_tp_irq_026', 'TP-IRQ-027': 'w_tp_irq_027', 'TP-IRQ-030': 'w_tp_irq_030', 'TP-IRQ-031': 'w_tp_irq_031', 'TP-IRQ-038': 'w_tp_irq_038', 'TP-IRQ-039': 'w_tp_irq_039', 'TP-IRQ-041': 'w_tp_irq_041', 'TP-IRQ-044': 'w_tp_irq_044', 'TP-IRQ-045': 'w_tp_irq_045', 'TP-IRQ-049': 'w_tp_irq_049', 'TP-IRQ-050': 'w_tp_irq_050', 'TP-IRQ-051': 'w_tp_irq_051', 'TP-IRQ-052': 'w_tp_irq_052', 'TP-IRQ-053': 'w_tp_irq_053', 'TP-IRQ-054': 'w_tp_irq_054', 'TP-IRQ-055': 'w_tp_irq_055', 'TP-IRQ-057': 'w_tp_irq_057', 'TP-IRQ-059': 'w_tp_irq_059', 'TP-IRQ-061': 'w_tp_irq_061', 'TP-IRQ-064': 'w_tp_irq_064', 'TP-IRQ-066': 'w_tp_irq_066', 'TP-IRQ-068': 'w_tp_irq_068', 'TP-IRQ-070': 'w_tp_irq_070', 'TP-IRQ-072': 'w_tp_irq_072', 'TP-IRQ-073': 'w_tp_irq_073', 'TP-IRQ-077': 'w_tp_irq_077', 'TP-IRQ-078': 'w_tp_irq_078', 'TP-IRQ-079': 'w_tp_irq_079', 'TP-IRQ-080': 'w_tp_irq_080', 'TP-ISA-024': 'w_tp_isa_024', 'TP-ISA-040': 'w_tp_isa_040', 'TP-ISA-051': 'w_tp_isa_051', 'TP-MUL-011': 'w_tp_mul_011', 'TP-MUL-023': 'w_tp_mul_023', 'TP-MUL-024': 'w_tp_mul_024', 'TP-PMC-001': 'w_tp_pmc_001', 'TP-PMC-002': 'w_tp_pmc_002', 'TP-PMC-011': 'w_tp_pmc_011', 'TP-PMC-013': 'w_tp_pmc_013', 'TP-PMC-016': 'w_tp_pmc_016', 'TP-PMC-024': 'w_tp_pmc_024', 'TP-PMC-028': 'w_tp_pmc_028', 'TP-PMC-034': 'w_tp_pmc_034', 'TP-PMC-047': 'w_tp_pmc_047', 'TP-PMC-058': 'w_tp_pmc_058', 'TP-PMC-059': 'w_tp_pmc_059', 'TP-PMC-060': 'w_tp_pmc_060', 'TP-PMP-053': 'w_tp_pmp_053', 'TP-PMP-077': 'w_tp_pmp_077', 'TP-PMP-082': 'w_tp_pmp_082', 'TP-PMP-091': 'w_tp_pmp_091', 'TP-PMP-105': 'w_tp_pmp_105', 'TP-PRV-018': 'w_tp_prv_018', 'TP-PRV-019': 'w_tp_prv_019', 'TP-REG-001': 'w_tp_reg_001', 'TP-REG-002': 'w_tp_reg_002', 'TP-REG-005': 'w_tp_reg_005', 'TP-REG-006': 'w_tp_reg_006', 'TP-REG-008': 'w_tp_reg_008', 'TP-REG-010': 'w_tp_reg_010', 'TP-REG-011': 'w_tp_reg_011', 'TP-REG-012': 'w_tp_reg_012', 'TP-REG-018': 'w_tp_reg_018', 'TP-REG-020': 'w_tp_reg_020', 'TP-REG-021': 'w_tp_reg_021', 'TP-REG-023': 'w_tp_reg_023', 'TP-REG-026': 'w_tp_reg_026', 'TP-REG-027': 'w_tp_reg_027', 'TP-TRG-019': 'w_tp_trg_019', 'TP-TRG-023': 'w_tp_trg_023', 'TP-TRG-025': 'w_tp_trg_025', 'TP-TRG-026': 'w_tp_trg_026', 'TP-TRG-027': 'w_tp_trg_027', 'TP-XIF-001': 'w_tp_xif_001', 'TP-XIF-002': 'w_tp_xif_002', 'TP-XIF-003': 'w_tp_xif_003', 'TP-XIF-004': 'w_tp_xif_004', 'TP-XIF-008': 'w_tp_xif_008', 'TP-XIF-009': 'w_tp_xif_009', 'TP-XIF-010': 'w_tp_xif_010', 'TP-XIF-011': 'w_tp_xif_011', 'TP-XIF-012': 'w_tp_xif_012', 'TP-XIF-014': 'w_tp_xif_014', 'TP-XIF-015': 'w_tp_xif_015', 'TP-XIF-016': 'w_tp_xif_016', 'TP-XIF-017': 'w_tp_xif_017'}
WITNESS_GROUP_OF = {'TP-BIT-036': 'gen_bit_multicycle', 'TP-BIT-042': 'gen_bit_random', 'TP-BIT-043': 'gen_bit_multicycle', 'TP-BTALU-001': 'gen_btalu_basic', 'TP-BTALU-012': 'gen_btalu_basic', 'TP-BTALU-018': 'gen_btalu_perf_b17_xfail', 'TP-CMP-057': 'gen_cmp_zcmp_events', 'TP-CMP-058': 'gen_cmp_zcmp_events', 'TP-CSR-029': 'gen_csr_trap_setup', 'TP-CSR-031': 'gen_csr_trap_setup_irq', 'TP-CSR-034': 'gen_csr_trap_handling', 'TP-CSR-085': 'gen_csr_cpuctrl', 'TP-CSR-090': 'gen_csr_cpuctrl', 'TP-CSR-100': 'gen_csr_storm', 'TP-DBG-003': 'gen_dbg_irq_mask', 'TP-DBG-004': 'gen_dbg_haltreq', 'TP-DBG-005': 'gen_dbg_haltreq', 'TP-DBG-006': 'gen_dbg_haltreq', 'TP-DBG-007': 'gen_dbg_haltreq', 'TP-DBG-008': 'gen_dbg_haltreq', 'TP-DBG-009': 'gen_dbg_haltreq', 'TP-DBG-011': 'gen_dbg_req_shape_info', 'TP-DBG-014': 'gen_dbg_haltreq', 'TP-DBG-021': 'gen_dbg_irq_mask_xfail', 'TP-DBG-030': 'gen_dbg_ebreak', 'TP-DBG-046': 'gen_dbg_step', 'TP-DBG-049': 'gen_dbg_step', 'TP-DBG-051': 'gen_dbg_step', 'TP-DBG-054': 'gen_dbg_step', 'TP-DBG-061': 'gen_dbg_irq_mask', 'TP-DBG-063': 'gen_dbg_mode_misc', 'TP-DBG-071': 'gen_dbg_haltreq', 'TP-DMEM-002': 'gen_dmem_proto_basic', 'TP-DMEM-004': 'gen_dmem_proto_basic', 'TP-DMEM-005': 'gen_dmem_latency', 'TP-DMEM-006': 'gen_dmem_proto_basic', 'TP-DMEM-007': 'gen_dmem_proto_basic', 'TP-DMEM-008': 'gen_dmem_proto_basic', 'TP-DMEM-019': 'gen_dmem_misaligned', 'TP-DMEM-020': 'gen_dmem_misaligned', 'TP-DMEM-021': 'gen_dmem_misaligned', 'TP-DMEM-022': 'gen_dmem_misaligned', 'TP-DMEM-027': 'gen_dmem_err', 'TP-DMEM-034': 'gen_dmem_err', 'TP-DMEM-037': 'gen_dmem_err', 'TP-DMEM-039': 'gen_dmem_intg', 'TP-DMEM-044': 'gen_dmem_ctx', 'TP-DMEM-046': 'gen_dmem_ctx', 'TP-DMEM-047': 'gen_dmem_ctx', 'TP-DMEM-049': 'gen_dmem_proto_basic', 'TP-DMEM-051': 'gen_dmem_ctx', 'TP-DMEM-056': 'gen_dmem_regime', 'TP-DMEM-057': 'gen_dmem_proto_basic', 'TP-DMEM-058': 'gen_dmem_proto_basic', 'TP-DMEM-059': 'gen_dmem_proto_basic', 'TP-DMEM-061': 'gen_dmem_ctx', 'TP-DMEM-062': 'gen_dmem_proto_basic_info', 'TP-DMEM-063': 'gen_dmem_err_info', 'TP-DMEM-064': 'gen_dmem_intg_xfail', 'TP-EXC-015': 'gen_exc_priority', 'TP-EXC-034': 'gen_exc_lsu_fault', 'TP-EXC-035': 'gen_exc_priority', 'TP-EXC-036': 'gen_exc_lsu_fault', 'TP-EXC-037': 'gen_exc_lsu_fault', 'TP-EXC-038': 'gen_exc_lsu_fault', 'TP-EXC-040': 'gen_exc_priority', 'TP-EXC-050': 'gen_exc_mret', 'TP-EXC-054': 'gen_exc_double_fault', 'TP-EXC-055': 'gen_exc_double_fault', 'TP-EXC-057': 'gen_exc_double_fault', 'TP-EXC-062': 'gen_exc_trap_state', 'TP-EXC-065': 'gen_exc_priority_info', 'TP-EXC-070': 'gen_exc_priority', 'TP-EXC-072': 'gen_exc_regime', 'TP-FE-008': 'gen_fe_align', 'TP-FE-012': 'gen_fe_redirect', 'TP-FE-013': 'gen_fe_redirect', 'TP-FE-014': 'gen_fe_redirect', 'TP-FE-016': 'gen_fe_backpressure', 'TP-FE-017': 'gen_fe_backpressure', 'TP-FE-022': 'gen_fe_fault', 'TP-FE-026': 'gen_fe_sleep', 'TP-IC-002': 'gen_ic_ram', 'TP-IC-003': 'gen_ic_ram', 'TP-IC-004': 'gen_ic_ram', 'TP-IC-005': 'gen_ic_ram', 'TP-IC-007': 'gen_ic_inval', 'TP-IC-008': 'gen_ic_inval', 'TP-IC-011': 'gen_ic_inval', 'TP-IC-015': 'gen_ic_inval', 'TP-IC-019': 'gen_ic_enable', 'TP-IC-020': 'gen_ic_enable', 'TP-IC-023': 'gen_ic_fill', 'TP-IC-024': 'gen_ic_fill', 'TP-IC-030': 'gen_ic_enable', 'TP-IC-031': 'gen_ic_enable', 'TP-IC-035': 'gen_ic_ecc', 'TP-IC-036': 'gen_ic_ecc', 'TP-IC-037': 'gen_ic_ecc', 'TP-IC-045': 'gen_ic_ram', 'TP-IC-046': 'gen_ic_ram', 'TP-IC-051': 'gen_ic_busy', 'TP-IC-052': 'gen_ic_busy', 'TP-IC-053': 'gen_ic_busy', 'TP-IC-057': 'gen_ic_enable', 'TP-IMEM-001': 'gen_imem_proto_basic', 'TP-IMEM-003': 'gen_imem_proto_basic', 'TP-IMEM-004': 'gen_imem_proto_basic', 'TP-IMEM-005': 'gen_imem_latency', 'TP-IMEM-006': 'gen_imem_proto_basic', 'TP-IMEM-007': 'gen_imem_proto_basic', 'TP-IMEM-008': 'gen_imem_latency', 'TP-IMEM-010': 'gen_imem_latency', 'TP-IMEM-014': 'gen_imem_fetch_err', 'TP-IMEM-016': 'gen_imem_fetch_err', 'TP-IMEM-017': 'gen_imem_redirect', 'TP-IMEM-018': 'gen_imem_redirect', 'TP-IMEM-022': 'gen_imem_gating', 'TP-IMEM-023': 'gen_imem_gating', 'TP-IMEM-025': 'gen_imem_gating', 'TP-IMEM-027': 'gen_imem_boot', 'TP-IMEM-033': 'gen_imem_latency', 'TP-IMEM-036': 'gen_imem_regime', 'TP-IMEM-037': 'gen_imem_regime', 'TP-IMEM-039': 'gen_imem_proto_basic', 'TP-IMEM-040': 'gen_imem_proto_basic_info', 'TP-IRQ-009': 'gen_irq_csr', 'TP-IRQ-011': 'gen_irq_csr', 'TP-IRQ-015': 'gen_irq_priority', 'TP-IRQ-021': 'gen_irq_timing', 'TP-IRQ-022': 'gen_irq_timing', 'TP-IRQ-023': 'gen_irq_timing', 'TP-IRQ-024': 'gen_irq_timing', 'TP-IRQ-025': 'gen_irq_timing', 'TP-IRQ-026': 'gen_irq_timing', 'TP-IRQ-027': 'gen_irq_timing', 'TP-IRQ-030': 'gen_irq_timing', 'TP-IRQ-031': 'gen_irq_priority', 'TP-IRQ-038': 'gen_irq_nmi', 'TP-IRQ-039': 'gen_irq_nmi', 'TP-IRQ-041': 'gen_irq_debug', 'TP-IRQ-044': 'gen_irq_nmi_int', 'TP-IRQ-045': 'gen_irq_nmi_int', 'TP-IRQ-049': 'gen_irq_wfi', 'TP-IRQ-050': 'gen_irq_wfi', 'TP-IRQ-051': 'gen_irq_wfi', 'TP-IRQ-052': 'gen_irq_wfi', 'TP-IRQ-053': 'gen_irq_wfi', 'TP-IRQ-054': 'gen_irq_wfi', 'TP-IRQ-055': 'gen_irq_wfi', 'TP-IRQ-057': 'gen_irq_wfi', 'TP-IRQ-059': 'gen_irq_reset', 'TP-IRQ-061': 'gen_irq_handler', 'TP-IRQ-064': 'gen_irq_timing', 'TP-IRQ-066': 'gen_irq_timing', 'TP-IRQ-068': 'gen_irq_wfi', 'TP-IRQ-070': 'gen_irq_csr', 'TP-IRQ-072': 'gen_irq_regime', 'TP-IRQ-073': 'gen_irq_regime', 'TP-IRQ-077': 'gen_irq_regime', 'TP-IRQ-078': 'gen_irq_debug', 'TP-IRQ-079': 'gen_irq_nmi', 'TP-IRQ-080': 'gen_irq_debug', 'TP-ISA-024': 'gen_isa_cti', 'TP-ISA-040': 'gen_isa_system', 'TP-ISA-051': 'gen_isa_illegal_info', 'TP-MUL-011': 'gen_mul_timing', 'TP-MUL-023': 'gen_mul_timing', 'TP-MUL-024': 'gen_mul_timing', 'TP-PMC-001': 'gen_pmc_mcycle', 'TP-PMC-002': 'gen_pmc_mcycle', 'TP-PMC-011': 'gen_pmc_minstret', 'TP-PMC-013': 'gen_pmc_minstret_xfail', 'TP-PMC-016': 'gen_pmc_minstret', 'TP-PMC-024': 'gen_pmc_ctrl', 'TP-PMC-028': 'gen_pmc_ctrl', 'TP-PMC-034': 'gen_pmc_hpm_event', 'TP-PMC-047': 'gen_pmc_hpm_csr', 'TP-PMC-058': 'gen_pmc_hpm_b17_br_xfail', 'TP-PMC-059': 'gen_pmc_hpm_b17_mul_xfail', 'TP-PMC-060': 'gen_pmc_hpm_b17_div_xfail', 'TP-PMP-053': 'gen_pmp_recfg', 'TP-PMP-077': 'gen_pmp_fetch_fault', 'TP-PMP-082': 'gen_pmp_data_fault', 'TP-PMP-091': 'gen_pmp_recfg', 'TP-PMP-105': 'gen_pmp_random_regime', 'TP-PRV-018': 'gen_prv_wfi', 'TP-PRV-019': 'gen_prv_wfi', 'TP-REG-001': 'gen_reg_knob_sweep', 'TP-REG-002': 'gen_reg_knob_sweep', 'TP-REG-005': 'gen_reg_knob_sweep', 'TP-REG-006': 'gen_reg_knob_sweep', 'TP-REG-008': 'gen_reg_knob_sweep', 'TP-REG-010': 'gen_reg_knob_sweep', 'TP-REG-011': 'gen_reg_knob_sweep', 'TP-REG-012': 'gen_reg_knob_sweep', 'TP-REG-018': 'gen_reg_schedule', 'TP-REG-020': 'gen_reg_inflight', 'TP-REG-021': 'gen_reg_inflight', 'TP-REG-023': 'gen_reg_inflight', 'TP-REG-026': 'gen_xcut_regime_sweep', 'TP-REG-027': 'gen_csr_mcounteren', 'TP-TRG-019': 'gen_trg_fire', 'TP-TRG-023': 'gen_trg_fire', 'TP-TRG-025': 'gen_trg_fire', 'TP-TRG-026': 'gen_trg_fire', 'TP-TRG-027': 'gen_trg_fire', 'TP-XIF-001': 'gen_xif_random', 'TP-XIF-002': 'gen_xif_random', 'TP-XIF-003': 'gen_xif_random', 'TP-XIF-004': 'gen_xif_random', 'TP-XIF-008': 'gen_xif_random', 'TP-XIF-009': 'gen_xif_random', 'TP-XIF-010': 'gen_xif_random', 'TP-XIF-011': 'gen_xif_random', 'TP-XIF-012': 'gen_xif_random', 'TP-XIF-014': 'gen_xif_random', 'TP-XIF-015': 'gen_xif_random', 'TP-XIF-016': 'gen_xif_fetch_enable', 'TP-XIF-017': 'gen_xif_reset'}
WITNESS_GROUPS = {'gen_bit_multicycle': 0, 'gen_bit_random': 1, 'gen_btalu_basic': 2, 'gen_btalu_perf_b17_xfail': 3, 'gen_cmp_zcmp_events': 4, 'gen_csr_trap_setup': 5, 'gen_csr_trap_setup_irq': 6, 'gen_csr_trap_handling': 7, 'gen_csr_cpuctrl': 8, 'gen_csr_storm': 9, 'gen_dbg_irq_mask': 10, 'gen_dbg_haltreq': 11, 'gen_dbg_req_shape_info': 12, 'gen_dbg_irq_mask_xfail': 13, 'gen_dbg_ebreak': 14, 'gen_dbg_step': 15, 'gen_dbg_mode_misc': 16, 'gen_dmem_proto_basic': 17, 'gen_dmem_latency': 18, 'gen_dmem_misaligned': 19, 'gen_dmem_err': 20, 'gen_dmem_intg': 21, 'gen_dmem_ctx': 22, 'gen_dmem_regime': 23, 'gen_dmem_proto_basic_info': 24, 'gen_dmem_err_info': 25, 'gen_dmem_intg_xfail': 26, 'gen_exc_priority': 27, 'gen_exc_lsu_fault': 28, 'gen_exc_mret': 29, 'gen_exc_double_fault': 30, 'gen_exc_trap_state': 31, 'gen_exc_priority_info': 32, 'gen_exc_regime': 33, 'gen_fe_align': 34, 'gen_fe_redirect': 35, 'gen_fe_backpressure': 36, 'gen_fe_fault': 37, 'gen_fe_sleep': 38, 'gen_ic_ram': 39, 'gen_ic_inval': 40, 'gen_ic_enable': 41, 'gen_ic_fill': 42, 'gen_ic_ecc': 43, 'gen_ic_busy': 44, 'gen_imem_proto_basic': 45, 'gen_imem_latency': 46, 'gen_imem_fetch_err': 47, 'gen_imem_redirect': 48, 'gen_imem_gating': 49, 'gen_imem_boot': 50, 'gen_imem_regime': 51, 'gen_imem_proto_basic_info': 52, 'gen_irq_csr': 53, 'gen_irq_priority': 54, 'gen_irq_timing': 55, 'gen_irq_nmi': 56, 'gen_irq_debug': 57, 'gen_irq_nmi_int': 58, 'gen_irq_wfi': 59, 'gen_irq_reset': 60, 'gen_irq_handler': 61, 'gen_irq_regime': 62, 'gen_isa_cti': 63, 'gen_isa_system': 64, 'gen_isa_illegal_info': 65, 'gen_mul_timing': 66, 'gen_pmc_mcycle': 67, 'gen_pmc_minstret': 68, 'gen_pmc_minstret_xfail': 69, 'gen_pmc_ctrl': 70, 'gen_pmc_hpm_event': 71, 'gen_pmc_hpm_csr': 72, 'gen_pmc_hpm_b17_br_xfail': 73, 'gen_pmc_hpm_b17_mul_xfail': 74, 'gen_pmc_hpm_b17_div_xfail': 75, 'gen_pmp_recfg': 76, 'gen_pmp_fetch_fault': 77, 'gen_pmp_data_fault': 78, 'gen_pmp_random_regime': 79, 'gen_prv_wfi': 80, 'gen_reg_knob_sweep': 81, 'gen_reg_schedule': 82, 'gen_reg_inflight': 83, 'gen_xcut_regime_sweep': 84, 'gen_csr_mcounteren': 85, 'gen_trg_fire': 86, 'gen_xif_random': 87, 'gen_xif_fetch_enable': 88, 'gen_xif_reset': 89}
WITNESS_COUNT = 220

MEMORY_MAP = {
    "boot_addr_default": 0x80000000,
    "boot_page_mask": 0xffffff00,
    "boot_reset_offset": 0x00000080,
    "boot_page": 0x80000000,
    "prog_size": 0x00100000,
    "dm_base": 0x1a110000,
    "dm_size": 0x00001000,
    "dm_halt": 0x1a110800,
    "dm_exception": 0x1a110808,
    "dm_budget": 0x00000800,
    "mmio_base": 0x8ffff000,
    "mmio_size": 0x00001000,
    "sig_addr": 0x8ffff000,
    "sig_size": 0x00000100,
    "irq_ack_addr": 0x8ffff100,
    "irq_ack_size": 0x00000004,
    "eot_addr": 0x8ffff104,
    "eot_size": 0x00000004,
    "phase_mark_addr": 0x8ffff108,
    "phase_mark_size": 0x00000004,
}

DEBUG_ONLY = [p["plusarg"] for p in PLUSARGS.values() if p["debug_only"]]
CHECKERS = [n[4:] for n in PLUSARGS if n.startswith("chk_") and n != "chk_all"]

def plusarg(name, value=None):
    """+gen_<name>[=value] as passed on the simv command line."""
    p = PLUSARGS[name]
    return f"+{p['plusarg']}" if value is None else f"+{p['plusarg']}={value}"
