#!/usr/bin/env python3
"""The minimum covergroup set the promoted fcov manifests reference (T-204; TB Infra implements in rank order, T-205).

Reads the committed testlist (every entry with an fcov_expectation_file), its manifests (dv/auto_dv/fcov_expectations/*.fcov.yaml:
bins are gen_<x>_cg.<coverpoint>.<bin> tokens; "# not_hit" header lines are excluded bins) and gen_fcov_plan.md (headers
"### CG-<AREA>-<nnn>: gen_cg_<x>", implemented as gen_<x>_cg, architecture Section 5). Writes a markdown report and a CSV: one row per
covergroup the manifests reference, ranked by distinct bins unlocked, with its plan anchor, the coverpoints / crosses and bins referenced,
the manifests that reference it and how many bins each, and the ledger covergroup marked. A manifest becomes verifiable only when every
covergroup it references exists, so the report also lists per manifest the covergroups it needs and the cumulative rank at which it is
complete.

Usage: gen_covergroup_set.py [--testlist F] [--fcov-dir D] [--fcov-plan F] [--md OUT.md] [--csv OUT.csv] [--plan-sha SHA]
"""
import re, csv, sys, argparse, pathlib, collections, yaml
R = pathlib.Path(__file__).resolve()
while not (R / 'dv/auto_dv/contract').is_dir(): R = R.parent
LEDGER_PLAN = 'CG-WIT-001'

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--testlist', default=str(R / 'dv/auto_dv/flow/gen_testlist.yaml')); ap.add_argument('--fcov-dir', default=str(R / 'dv/auto_dv/fcov_expectations'))
    ap.add_argument('--fcov-plan', default=str(R / 'dv/auto_dv/docs/gen_fcov_plan.md')); ap.add_argument('--md', default=str(R / 'dv/auto_dv/evidence/gen_round0_covergroup_set.md'))
    ap.add_argument('--csv', default=str(R / 'dv/auto_dv/evidence/gen_round0_covergroup_set.csv')); ap.add_argument('--plan-sha', default='working tree')
    a = ap.parse_args()
    plan = pathlib.Path(a.fcov_plan).read_text()
    plan_of_impl = {}; anchor = {}
    for i, line in enumerate(plan.splitlines(), 1):
        m = re.match(r'^### (CG-[A-Z]+-\d{3}): (gen_cg_\w+)', line)
        if m: plan_of_impl['gen_' + m.group(2)[len('gen_cg_'):] + '_cg'] = m.group(1); anchor[m.group(1)] = f'gen_fcov_plan.md:{i} {line.strip()}'
    tl = yaml.safe_load(open(a.testlist))
    entries = [e for e in tl['tests'] if e.get('fcov_expectation_file')]
    per_cg = collections.defaultdict(lambda: {'bins': set(), 'cps': collections.defaultdict(set), 'manifests': collections.Counter()})
    per_man = {}
    for e in sorted(entries, key=lambda e: e['name']):
        p = R / e['fcov_expectation_file']
        if not p.exists(): sys.exit(f'{e["name"]}: manifest {p} missing')
        txt = p.read_text(); nh = set(re.findall(r'^# not_hit (\S+):', txt, re.M))
        bins = list((yaml.safe_load(txt) or {}).get('bins') or [])
        cgs = collections.Counter()
        for b in bins:
            cg, cp, bn = b.split('.', 2)
            per_cg[cg]['bins'].add(f'{cp}.{bn}'); per_cg[cg]['cps'][cp].add(bn); per_cg[cg]['manifests'][e['name']] += 1; cgs[cg] += 1
        per_man[e['name']] = {'bins': len(bins), 'not_hit': len(nh), 'cgs': cgs, 'tier': e.get('tier'), 'measured': e.get('measured')}
    ranked = sorted(per_cg.items(), key=lambda kv: (-len(kv[1]['bins']), kv[0]))
    rank_of = {cg: i + 1 for i, (cg, _) in enumerate(ranked)}
    complete_at = {m: max(rank_of[cg] for cg in d['cgs']) if d['cgs'] else 0 for m, d in per_man.items()}
    unknown = [cg for cg, _ in ranked if cg not in plan_of_impl]
    rows = []
    for rk, (cg, d) in enumerate(ranked, 1):
        pid = plan_of_impl.get(cg, 'UNKNOWN (no plan header)')
        done_here = sorted(m for m, r in complete_at.items() if r == rk)
        rows.append({'rank': rk, 'covergroup': cg, 'plan_id': pid, 'ledger': 'yes' if pid == LEDGER_PLAN else 'no', 'bins_referenced': len(d['bins']),
                     'coverpoints_referenced': len(d['cps']), 'coverpoints': '; '.join(f"{cp} ({len(bs)})" for cp, bs in sorted(d['cps'].items())),
                     'manifests': len(d['manifests']), 'manifest_bins': '; '.join(f"{m} ({n})" for m, n in sorted(d['manifests'].items())),
                     'manifests_completed_at_this_rank': '; '.join(done_here) or '-', 'plan_anchor': anchor.get(pid, '-')})
    total_bins = sum(r['bins_referenced'] for r in rows)
    hdr = f"""# Minimum covergroup set referenced by the promoted fcov manifests (T-204; implementation order for TB Infra, T-205)

GENERATED by dv/auto_dv/tools/gen_covergroup_set.py from dv/auto_dv/flow/gen_testlist.yaml, the {len(entries)} manifests it names under
dv/auto_dv/fcov_expectations/ and gen_fcov_plan.md at {a.plan_sha} (regeneration command, byte for byte: python3 dv/auto_dv/tools/gen_covergroup_set.py
--plan-sha {a.plan_sha}). Ranking: distinct bins referenced across the manifests (a bin is counted once per covergroup even when several
manifests declare it); bins under a manifest's "# not_hit" header are excluded and not counted. A manifest is verifiable only when every
covergroup it references exists (a missing covergroup makes the per-test URG report lack the group, LOG-046), so the column "manifests
completed at this rank" names the manifests that become fully verifiable once the covergroups ranked 1..N exist. The ledger covergroup
{LEDGER_PLAN} (gen_wit_cycle_clause_cg, T-179) is marked; its bins are witness bins, excluded from the score by name. Plan anchors are the
gen_fcov_plan.md headers (file:line). Covergroups without a plan header: {len(unknown)} ({', '.join(unknown) or 'none'}).

Totals: {len(rows)} covergroups, {total_bins} distinct referenced bins, {len(entries)} manifests ({sum(d['bins'] for d in per_man.values())} declared bins in total,
{sum(d['not_hit'] for d in per_man.values())} bins_not_hit excluded).

| Rank | Covergroup (SV) | Plan id | Ledger | Bins referenced | Coverpoints / crosses referenced (bins each) | Manifests (bins each) | Manifests completed at this rank | Plan anchor |
|---|---|---|---|---|---|---|---|---|
"""
    body = ''.join(f"| {r['rank']} | {r['covergroup']} | {r['plan_id']} | {r['ledger']} | {r['bins_referenced']} | {r['coverpoints']} | {r['manifest_bins']} | {r['manifests_completed_at_this_rank']} | {r['plan_anchor']} |\n" for r in rows)
    mt = "\n## Per manifest\n\n| Manifest (test) | Tier | measured | Declared bins | bins_not_hit | Covergroups needed | Complete at rank |\n|---|---|---|---|---|---|---|\n"
    for m, d in sorted(per_man.items(), key=lambda kv: (complete_at[kv[0]], kv[0])):
        mt += f"| {m} | {d['tier']} | {str(bool(d['measured'])).lower()} | {d['bins']} | {d['not_hit']} | {len(d['cgs'])}: {'; '.join(f'{cg} ({n})' for cg, n in sorted(d['cgs'].items()))} | {complete_at[m]} |\n"
    ledger_impl = 'gen_wit_cycle_clause_cg'
    if ledger_impl not in per_cg:
        mt += (f"\n## Ledger covergroup\n\n{LEDGER_PLAN} ({ledger_impl}, {anchor.get(LEDGER_PLAN, '-')}) is referenced by NO promoted manifest today: the released witness bins belong to"
               f" unbuilt groups, and the one released item of a promoted test (TP-CSR-029, gen_test_csr_trap_setup) carries its witness bin under bins_not_hit (rule g)."
               f" It enters this set the moment a promoted manifest declares a witness bin; its implementation is T-179 regardless, because the witness score (Section 0)"
               f" depends on it.\n")
    out = hdr + body + mt
    assert not [c for c in out.encode() if c > 127]
    pathlib.Path(a.md).write_text(out)
    with open(a.csv, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
    print(f'{len(rows)} covergroups, {total_bins} referenced bins, {len(entries)} manifests; ledger rank {rank_of.get("gen_wit_cycle_clause_cg", "-")}; unknown {unknown}; wrote {a.md}, {a.csv}')

if __name__ == '__main__': main()
