// gen_tb.f: TB filelist of gen_tb_top (compile after dv/auto_dv/tb/gen_rtl.f; clone-root relative).
+incdir+dv/auto_dv/tb
+incdir+dv/auto_dv/env
dv/auto_dv/tb/gen_tb_pkg.sv
dv/auto_dv/tb/gen_dut_top.sv
dv/auto_dv/tb/gen_protocol_props.sv
dv/auto_dv/tb/gen_b8_probe.sv
dv/auto_dv/tb/gen_ic_lookup_probe.sv
dv/auto_dv/tb/gen_binds.sv
dv/auto_dv/tb/gen_bridge_if.sv
dv/auto_dv/tb/gen_bus_if.sv
dv/auto_dv/tb/gen_scrkey_if.sv
dv/auto_dv/tb/gen_ctrl_if.sv
dv/auto_dv/tb/gen_icache_ram.sv
dv/auto_dv/tb/gen_rvfi_if.sv
dv/auto_dv/tb/gen_irq_if.sv
dv/auto_dv/tb/gen_dbg_if.sv
dv/auto_dv/tb/gen_misc_if.sv
dv/auto_dv/env/gen_cfg_pkg.sv
dv/auto_dv/env/gen_export_pkg.sv
dv/auto_dv/env/gen_mem_pkg.sv
dv/auto_dv/env/gen_agents_pkg.sv
dv/auto_dv/isa/gen_isa_dpi_pkg.sv
dv/auto_dv/env/gen_rvfi_pkg.sv
dv/auto_dv/env/gen_fcov_pkg.sv
dv/auto_dv/env/gen_checkers_pkg.sv
dv/auto_dv/env/gen_counter_model.sv
dv/auto_dv/env/gen_env_pkg.sv
dv/auto_dv/tb/gen_tb_top.sv
