#!/usr/bin/env python3
"""Derive the DUT RTL filelist (dv/auto_dv/tb/gen_rtl.f) from the .core files via fusesoc.

The DUT is ibex_core plus ibex_register_file_ff (DV_prompt.txt Section 2 ruling). fusesoc
resolves lowrisc:ibex:ibex_core and its prim dependencies; the register file is appended from
ibex_top.core's file set because no .core target describes the ruled DUT. The default fusesoc
target maps abstract prims to prim_xilinx for non-Verilator tools (ibex_top.core targets), so
prim_xilinx paths are substituted with the prim_generic implementation of the same module name.

Paths in the output are relative to the clone root: run vcs from the clone root
(docs/dv/SIM_RECIPE.md runs every command there). Defines (+define+RVFI, the config defines)
belong to the compile command, not to this list.

Usage (from a login shell with ci/env.sh sourced, so fusesoc from .venv is on PATH):
    python3 dv/auto_dv/tb/gen_filelist.py            # regenerate dv/auto_dv/tb/gen_rtl.f
    python3 dv/auto_dv/tb/gen_filelist.py --check    # exit 1 if the committed list is stale
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

CORE_NAME = "lowrisc:ibex:ibex_core"
# Second DUT module by ruling; ibex_top.core files_rtl names it (not reachable through ibex_core.core).
EXTRA_DUT_FILES = ["rtl/ibex_register_file_ff.sv"]
PRIM_XILINX_DIR = "vendor/lowrisc_ip/ip/prim_xilinx/rtl"
PRIM_GENERIC_DIR = "vendor/lowrisc_ip/ip/prim_generic/rtl"
# Xilinx-only packages have no generic counterpart and nothing in the DUT needs them.
DROP_BASENAMES = {"prim_xilinx_pkg.sv"}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def run_fusesoc(root: Path, work_root: Path) -> Path:
    fusesoc = shutil.which("fusesoc")
    if fusesoc is None:
        sys.exit("ERROR: fusesoc not on PATH; source ci/env.sh (venv) first")
    cmd = [fusesoc, "--cores-root", str(root), "run", "--setup", "--no-export", "--tool=vcs",
           "--target=default", "--work-root", str(work_root), CORE_NAME]
    r = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"ERROR: fusesoc failed ({r.returncode}):\n{r.stdout[-2000:]}\n{r.stderr[-2000:]}")
    scr = sorted(work_root.glob("*.scr"))
    if len(scr) != 1:
        sys.exit(f"ERROR: expected one .scr in {work_root}, found {scr}")
    return scr[0]


def fusesoc_version() -> str:
    r = subprocess.run(["fusesoc", "--version"], capture_output=True, text=True)
    return r.stdout.strip() or "unknown"


def convert(scr: Path, root: Path) -> tuple[list[str], list[str]]:
    """Return (lines, notes): repo-relative +incdir+ and file entries, and the substitutions made."""
    lines: list[str] = []
    notes: list[str] = []
    for raw in scr.read_text().splitlines():
        entry = raw.strip()
        if not entry:
            continue
        is_inc = entry.startswith("+incdir+")
        path_txt = entry[len("+incdir+"):] if is_inc else entry
        abs_path = (scr.parent / path_txt).resolve()
        try:
            rel = abs_path.relative_to(root)
        except ValueError:
            sys.exit(f"ERROR: {abs_path} is outside the clone root {root}")
        rel_s = rel.as_posix()
        if rel.name in DROP_BASENAMES:
            notes.append(f"dropped {rel_s}")
            continue
        if rel_s.startswith(PRIM_XILINX_DIR + "/"):
            generic = f"{PRIM_GENERIC_DIR}/{rel.name}"
            if not (root / generic).is_file():
                sys.exit(f"ERROR: no prim_generic counterpart for {rel_s}")
            notes.append(f"{rel_s} -> {generic}")
            rel_s = generic
        if not is_inc and not (root / rel_s).is_file():
            sys.exit(f"ERROR: listed file missing: {rel_s}")
        if is_inc and not (root / rel_s).is_dir():
            sys.exit(f"ERROR: include dir missing: {rel_s}")
        lines.append(("+incdir+" + rel_s) if is_inc else rel_s)
    for extra in EXTRA_DUT_FILES:
        if not (root / extra).is_file():
            sys.exit(f"ERROR: extra DUT file missing: {extra}")
        if extra not in lines:
            lines.append(extra)
    return lines, notes


def render(lines: list[str], notes: list[str]) -> str:
    hdr = [
        "// gen_rtl.f: DUT RTL filelist (ibex_core + ibex_register_file_ff), paths relative to the",
        "// clone root. GENERATED by dv/auto_dv/tb/gen_filelist.py from " + CORE_NAME + " via",
        f"// {fusesoc_version()}; do not edit by hand, regenerate (--check verifies).",
        "// Compile-time defines (+define+RVFI, util/ibex_config.py opentitan vcs_opts) are NOT here.",
    ]
    if notes:
        hdr.append("// Substitutions applied to the fusesoc default-target output:")
        hdr += [f"//   {n}" for n in notes]
    return "\n".join(hdr + lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=None, help="output path (default dv/auto_dv/tb/gen_rtl.f)")
    ap.add_argument("--check", action="store_true", help="compare against the existing file; exit 1 on drift")
    args = ap.parse_args()
    root = repo_root()
    out = args.out or (root / "dv/auto_dv/tb/gen_rtl.f")
    with tempfile.TemporaryDirectory(prefix="gen_filelist_") as tmp:
        scr = run_fusesoc(root, Path(tmp))
        lines, notes = convert(scr, root)
    text = render(lines, notes)
    if args.check:
        if not out.is_file() or out.read_text() != text:
            print(f"STALE: {out} differs from the fusesoc-derived list; regenerate", file=sys.stderr)
            return 1
        print(f"OK: {out} is current ({len(lines)} entries)")
        return 0
    out.write_text(text)
    print(f"wrote {out} ({len(lines)} entries, {len(notes)} substitutions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
