#!/usr/bin/env python3
"""Results dashboard: dv/auto_dv/docs/gen_dashboard.md from the regression manifests
(<out root>/regress_*/manifest.yaml) and the run-request results
(dv/auto_dv/work/runtime/results/*/manifest.yaml).

Metrics collected (agent_team_prompt.txt, Runtime Manager section; dashboard_metrics.md does
not exist): per-round coverage per metric, pass or fail per test, runtime per test, closure-round
count, LSF cost per round. A closure round is a purpose-4 regression (full tier with coverage).
A metric URG did not report is printed as n/a (DV_prompt Section 4).

Usage:
    gen_dashboard.py [--out FILE] [--out-root DIR] [--results-dir DIR]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import gen_flow_const as C
import gen_flow_util as U


def load_manifests(out_root: Path, results_dir: Path) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]]]:
    """Every finished regression manifest, deduplicated by outdir, oldest first."""
    seen: dict[str, dict[str, Any]] = {}
    for p in sorted(out_root.glob("regress_*/manifest.yaml")):
        m = U.load_yaml(p)
        if isinstance(m, dict) and m.get("kind") == "regression":
            m["_path"] = str(p)
            seen[m.get("outdir") or str(p.parent)] = m
    requests: dict[str, dict[str, Any]] = {}
    for p in sorted(results_dir.glob("*/manifest.yaml")):
        r = U.load_yaml(p)
        if isinstance(r, dict):
            requests[r.get("request") or p.parent.name] = r
            reg = r.get("regress_manifest")
            if reg and Path(reg).is_file() and str(Path(reg).parent) not in seen:
                m = U.load_yaml(Path(reg))
                if isinstance(m, dict) and m.get("kind") == "regression":
                    m["_path"] = reg
                    seen[m.get("outdir") or str(Path(reg).parent)] = m
    regs = sorted(seen.values(), key=lambda m: m.get("started_utc") or "")
    for m in regs:
        m["_request_record"] = requests.get(m.get("request") or "")
    return regs, requests


def fmt(v: Any) -> str:
    if v is None:
        return "-"
    if isinstance(v, float):
        return f"{v:.2f}"
    return str(v)


def metric_cell(cov: dict[str, Any], key: str) -> str:
    v = cov.get(key, C.NOT_APPLICABLE)
    if v == C.NOT_APPLICABLE or v is None:
        return C.NOT_APPLICABLE
    ratio = (cov.get("ratios") or {}).get(key)
    return f"{v:.2f}" + (f" ({ratio})" if ratio else "")


def dut_scope_row(m: dict[str, Any]) -> dict[str, Any]:
    """Code metrics from the DUT instance row of hierarchy.txt; functional coverage (GROUP) from
    the grand total, because covergroups are TB-side gen_ instances that never appear under the
    DUT instance (the Test Writer's gen_ namespace is the whole functional set). No fallback to
    the grand total for code metrics: a missing DUT row shows n/a with a parse_error note."""
    cov = m.get("coverage") or {}
    totals = cov.get("totals") or {}
    scopes = cov.get("dut_scope") or {}
    row: dict[str, Any] = {}
    if len(scopes) > 1:
        # No combining rule for several DUT scopes exists yet (P-04 pending): report n/a, never the first.
        return {m: C.NOT_APPLICABLE for m in C.URG_METRICS} | {"ratios": {}, "parse_error": f"{len(scopes)} DUT scopes, no combining rule"}
    if scopes:
        first = next(iter(scopes.values()))
        if isinstance(first, dict) and "parse_error" not in first:
            row = dict(first)
    if not row:
        return {m: C.NOT_APPLICABLE for m in C.URG_METRICS} | {"ratios": {}, "parse_error": "DUT-scope row missing"}
    row["group"] = totals.get("group", C.NOT_APPLICABLE)
    ratios = dict(row.get("ratios") or {})
    if (totals.get("ratios") or {}).get("group"):
        ratios["group"] = totals["ratios"]["group"]
    row["ratios"] = ratios
    return row


def delta(cur: Any, prev: Any) -> str:
    if isinstance(cur, float) and isinstance(prev, float):
        d = cur - prev
        return f"{d:+.2f}"
    return "-"


def render(regs: list[dict[str, Any]], requests: dict[str, dict[str, Any]], out_root: Path) -> str:
    L: list[str] = []
    L.append("# Regression dashboard (generated by dv/auto_dv/flow/gen_dashboard.py)")
    L.append("")
    L.append(f"Generated (UTC): {U.now_utc()}. Build configuration: `{C.BUILD_CONFIG}`. Out root: `{out_root}`.")
    L.append(f"Sources: {len(regs)} regression manifest(s), {len(requests)} run-request result(s). "
             "Code-coverage numbers are the URG DUT-scope row (`<tb_top>.<dut_instance>` in hierarchy.txt); "
             "functional coverage (Group) is the grand total, the gen_ covergroups being TB-side; "
             "`n/a` means URG did not report the metric (never 0 or 100, DV_prompt Section 4). "
             "Ratios are covered/total objects.")
    L.append("")
    L.append("## 1. Closure rounds (from dv/auto_dv/evidence/gen_rounds.yaml, written by gen_round.py)")
    L.append("")
    index = U.load_yaml(C.ROUND_INDEX) if C.ROUND_INDEX.is_file() else None
    if index is not None:
        rnds = index.get("rounds") or []
        L.append(f"Closure-round count: **{len(rnds)}**. Gate {C.GATE_PCT} percent per gated metric; gain rule G = "
                 f"{index.get('G', C.ROUND_GAIN_G)} points on any gated metric; stop after N = {index.get('N', C.ROUND_NO_GAIN_N)} "
                 f"rounds without gain. n/a = URG did not report the metric (excluded from gate and gain).")
        L.append("")
        if rnds:
            L.append("| Round | Label | Date (UTC) | Runs pass/planned | Line | Cond | Toggle | FSM | Branch | Assert | Group | Max gain (pts) | Shows gain | No-gain streak | Evidence |")
            L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
            for e in rnds:
                mt = e.get("metrics") or {}
                g = e.get("gain") or {}
                L.append(f"| {e['round']} | {e.get('label') or '-'} | {e['date_utc']} | "
                         f"{(e.get('runs') or {}).get('pass', '-')}/{(e.get('runs') or {}).get('planned', '-')} | "
                         + " | ".join(metric_cell(mt, k) for k in C.URG_METRICS)
                         + f" | {fmt(g.get('max_gain'))} | {g.get('shows_gain')} | {e.get('no_gain_streak')} | `{e['evidence_dir']}` |")
            last = rnds[-1]
            L.append("")
            L.append(f"Stopping rule fired: **{last.get('stopping_rule_fired')}** (after round {last['round']}).")
        else:
            L.append("No closure round has run yet.")
        drs = index.get("dry_runs") or []
        if drs:
            L.append("")
            L.append("Dry runs of the procedure (UNMEASURED, check tier; not rounds, not counted):")
            L.append("")
            L.append("| Dry run | Date (UTC) | Source | Line | Cond | Toggle | FSM | Branch | Assert | Group | Evidence |")
            L.append("|---|---|---|---|---|---|---|---|---|---|---|")
            for e in drs:
                mt = e.get("metrics") or {}
                L.append(f"| {e.get('regress_tag')} | {e['date_utc']} | {e.get('source')} | "
                         + " | ".join(metric_cell(mt, k) for k in C.URG_METRICS) + f" | `{e['evidence_dir']}` |")
        L.append("")
    rounds = [m for m in regs if m.get("purpose") == 4 and m.get("status") == "done"]
    L.append("### 1a. Purpose-4 regressions seen in the out root (cross-check of the index)")
    L.append("")
    L.append(f"Purpose-4 full regressions with coverage in the out root: **{len(rounds)}**.")
    L.append("")
    if rounds:
        L.append("| Round | Tag / request | Started (UTC) | Runs pass/fail/total | Line | Cond | Toggle | FSM | Branch | Assert | Group | Gain vs prev (max pp) | LSF jobs | LSF CPU s | LSF slot s |")
        L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        prev: dict[str, Any] | None = None
        for i, m in enumerate(rounds, start=1):
            cov = dut_scope_row(m)
            s = m.get("summary") or {}
            cost = m.get("lsf_cost") or {}
            gain = "-"
            if prev is not None:
                ds = [cov.get(k) - prev.get(k) for k in C.URG_METRICS
                      if isinstance(cov.get(k), float) and isinstance(prev.get(k), float)]
                gain = f"{max(ds):+.2f}" if ds else "-"
            L.append(f"| {i} | {m.get('tag') or m.get('request') or '-'} | {m.get('started_utc')} | "
                     f"{s.get('pass', 0)}/{s.get('fail', 0) + s.get('timeout', 0) + s.get('not_run', 0)}/{s.get('planned', 0)} | "
                     + " | ".join(metric_cell(cov, k) for k in C.URG_METRICS)
                     + f" | {gain} | {cost.get('jobs', '-')} | {fmt(cost.get('cpu_s'))} | {fmt(cost.get('slot_s'))} |")
            prev = cov
    else:
        L.append("None yet.")
    L.append("")
    L.append("## 2. Coverage per regression (every coverage-bearing run, newest last)")
    L.append("")
    covregs = [m for m in regs if (m.get("coverage") or {}).get("dashboard_txt")]
    if covregs:
        L.append("| Regression | Purpose | Scope | Tests in report | Line | Cond | Toggle | FSM | Branch | Assert | Group | URG report |")
        L.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
        for m in covregs:
            cov = dut_scope_row(m)
            tot = (m.get("coverage") or {}).get("totals") or {}
            sc = m.get("scope") or {}
            scope_txt = sc.get("tier") or sc.get("tests") or (" ".join(sc.get("repro") or []) or "-")
            L.append(f"| {m.get('tag') or Path(m.get('outdir', '')).name} | {m.get('purpose') or '-'} | {scope_txt} | "
                     f"{tot.get('tests_in_report', '-')} | " + " | ".join(metric_cell(cov, k) for k in C.URG_METRICS)
                     + f" | `{(m.get('coverage') or {}).get('report_dir')}` |")
    else:
        L.append("No coverage report yet.")
    L.append("")
    L.append("## 3. Pass/fail and runtime per test (latest run of each test+seed, all regressions)")
    L.append("")
    latest: dict[tuple[str, int], dict[str, Any]] = {}
    history: dict[str, dict[str, Any]] = {}
    for m in regs:
        for r in m.get("runs") or []:
            key = (r["test"], int(r["seed"]))
            latest[key] = dict(r, _reg=m.get("tag") or Path(m.get("outdir", "")).name)
            h = history.setdefault(r["test"], {"runs": 0, "pass": 0, "wall": []})
            h["runs"] += 1
            if r.get("verdict") in (C.VERDICT_PASS, C.VERDICT_XFAIL):
                h["pass"] += 1
            if isinstance(r.get("wall_s"), (int, float)):
                h["wall"].append(float(r["wall_s"]))
    if latest:
        L.append("| Test | Seed | Verdict | Reason | fcov expectation | Wall s | LSF job | Owner | Regression | sim.log |")
        L.append("|---|---|---|---|---|---|---|---|---|---|")
        for (t, s), r in sorted(latest.items()):
            lsf = r.get("lsf") or {}
            fc = r.get("fcov_check") or {}
            if not r.get("fcov_expectation_file"):
                fcov = "no manifest"
            elif not fc or fc.get("status") == "NO_MANIFEST":
                fcov = f"not checked (verdict {r.get('verdict')})"
            else:
                fcov = f"{fc.get('status')} {fc.get('hit', 0)}/{fc.get('declared', 0)} bins"
            L.append(f"| {t} | {s} | {r.get('verdict')} | {str(r.get('reason') or '')[:80]} | {fcov} | {fmt(r.get('wall_s'))} | "
                     f"{lsf.get('job_id') or r.get('lsf_job_id') or '-'} | {r.get('owner') or '-'} | {r['_reg']} | `{r.get('sim_log')}` |")
        L.append("")
        L.append("| Test | Runs | Passing runs | Pass rate % | Mean wall s | Max wall s |")
        L.append("|---|---|---|---|---|---|")
        for t, h in sorted(history.items()):
            mean = sum(h["wall"]) / len(h["wall"]) if h["wall"] else None
            mx = max(h["wall"]) if h["wall"] else None
            rate = 100.0 * h["pass"] / h["runs"] if h["runs"] else None
            L.append(f"| {t} | {h['runs']} | {h['pass']} | {fmt(rate)} | {fmt(mean)} | {fmt(mx)} |")
    else:
        L.append("No run recorded yet.")
    L.append("")
    L.append("## 4. LSF cost per regression")
    L.append("")
    L.append("| Regression | Purpose | Requester | Jobs | CPU s | Wall s (sum) | Slot s | Pend s (sum) | Regression wall s | fcov checked/unmet/unverifiable | Runs w/o fcov manifest | Status |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for m in regs:
        cost = m.get("lsf_cost") or {}
        sm = m.get("summary") or {}
        ft = ((m.get("fcov") or {}).get("totals")) or {}
        fcov = f"{ft.get('checked', 0)}/{ft.get('unmet', 0)}/{ft.get('unverifiable', 0)}" if ft else "-"
        L.append(f"| {m.get('tag') or Path(m.get('outdir', '')).name} | {m.get('purpose') or '-'} | {m.get('requester') or '-'} | "
                 f"{cost.get('jobs', '-')} | {fmt(cost.get('cpu_s'))} | {fmt(cost.get('wall_s'))} | {fmt(cost.get('slot_s'))} | "
                 f"{fmt(cost.get('pend_s'))} | {fmt(m.get('wall_s'))} | {fcov} | {sm.get('runs_without_fcov_manifest', '-')} | {m.get('status')} |")
    L.append("")
    L.append("## 5. Run requests served")
    L.append("")
    if requests:
        L.append("| Request | Requester | Purpose | Decision | Reason / summary | Manifest |")
        L.append("|---|---|---|---|---|---|")
        for name, r in sorted(requests.items()):
            s = r.get("summary") or {}
            why = r.get("refusal_reason") or (f"pass {s.get('pass')} fail {s.get('fail')} of {s.get('planned')}"
                                             if s else r.get("status"))
            L.append(f"| {name} | {r.get('requester') or '-'} | {r.get('purpose') or '-'} | {r.get('scope_decision') or '-'} | "
                     f"{str(why)[:100]} | `{C.RESULTS_DIR / name / C.RESULTS_MANIFEST}` |")
    else:
        L.append("No run request served yet.")
    L.append("")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=C.DASHBOARD_MD)
    ap.add_argument("--out-root", type=Path, default=C.OUT_DIR)
    ap.add_argument("--results-dir", type=Path, default=C.RESULTS_DIR)
    a = ap.parse_args()
    if C.DASHBOARD_METRICS_MD.is_file():
        U.log(f"note: {C.DASHBOARD_METRICS_MD} exists; extend this script to collect what it lists")
    regs, requests = load_manifests(a.out_root, a.results_dir)
    text = render(regs, requests, a.out_root)
    if any(ord(ch) > 127 for ch in text):
        U.die("dashboard text is not ASCII-only")
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(text, encoding="ascii")
    U.log(f"wrote {a.out} ({len(regs)} regressions, {len(requests)} requests)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
